#!/usr/bin/env node
// Test: tools/gen_config.mjs generates valid config_parser.h + config_parser.cpp
//
// Runs codegen in --check mode (verifies generated files match) and inspects
// the generated header for expected symbols.

import { readFileSync, existsSync } from 'fs';
import { execSync } from 'child_process';
import { dirname, join } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, '..', '..');
const header = join(root, 'src', 'config', 'config_parser.h');
const source = join(root, 'src', 'config', 'config_parser.cpp');

let passed = 0;
let failed = 0;

function test(name, fn) {
  try {
    fn();
    console.log(`  PASS: ${name}`);
    passed++;
  } catch (e) {
    console.error(`  FAIL: ${name} — ${e.message}`);
    failed++;
  }
}

function assert(cond, msg) {
  if (!cond) throw new Error(msg);
}

console.log('=== gen_config.mjs tests ===\n');

// 1. Codegen runs without error
test('codegen runs successfully', () => {
  execSync('node tools/gen_config.mjs', { cwd: root, stdio: 'pipe' });
});

// 2. --check mode passes (generated files up to date)
test('--check mode passes', () => {
  execSync('node tools/gen_config.mjs --check', { cwd: root, stdio: 'pipe' });
});

// 3. Generated files exist
test('config_parser.h exists', () => {
  assert(existsSync(header), 'config_parser.h not found');
});

test('config_parser.cpp exists', () => {
  assert(existsSync(source), 'config_parser.cpp not found');
});

const h = readFileSync(header, 'utf8');
const cpp = readFileSync(source, 'utf8');

// 4. Header has AUTO-GENERATED marker
test('header has auto-generated marker', () => {
  assert(h.includes('AUTO-GENERATED by tools/gen_config.mjs'), 'missing marker');
});

// 5. Enums present
for (const e of ['GpuType', 'GpuRole', 'Architecture', 'WeightQuant', 'AttentionQuant',
                  'KvCacheQuant', 'GatingQuant', 'EvictionPolicy', 'IoEngine',
                  'RankingStrategy', 'LayerSkipMethod', 'GemmBackend']) {
  test(`enum class ${e} present`, () => {
    assert(h.includes(`enum class ${e}`), `missing enum class ${e}`);
  });
}

// 6. Renamed enum values present (C++ keyword avoidance)
test('static_calibration enum value present', () => {
  assert(h.includes('static_calibration'), 'missing static_calibration');
});

test('default_scaling enum value present', () => {
  assert(h.includes('default_scaling'), 'missing default_scaling');
});

// 7. Structs present
for (const s of ['Config', 'GpuConfig', 'ModelConfig', 'HardwareConfig',
                  'MemoryConfig', 'SpeculationConfig', 'ServingConfig',
                  'VramAllocationConfig', 'RopeScalingConfig']) {
  test(`struct ${s} present`, () => {
    assert(h.includes(`struct ${s}`), `missing struct ${s}`);
  });
}

// 8. x-override fields are plain types (not std::optional)
test('vram_gb is plain double (x-override)', () => {
  assert(h.includes('double vram_gb'), 'vram_gb not plain double');
  assert(!h.includes('optional<double> vram_gb'), 'vram_gb should not be optional');
});

test('pcie_gen is plain int (x-override)', () => {
  assert(h.includes('int pcie_gen'), 'pcie_gen not plain int');
});

test('tp_array is vector<int> (x-override)', () => {
  assert(h.includes('std::vector<int> tp_array'), 'tp_array not vector<int>');
  assert(!h.includes('optional') || !h.match(/optional.*tp_array/), 'tp_array should not be optional');
});

// 9. Variant types present
test('LayerPinSpec variant present', () => {
  assert(h.includes('LayerPinSpec'), 'missing LayerPinSpec');
});

test('AutoOrInt variant present', () => {
  assert(h.includes('AutoOrInt'), 'missing AutoOrInt');
});

// 10. Const fields NOT in structs
test('capture_expert_ffn not in CudaGraphsConfig', () => {
  // Should not appear as a struct member
  const cudaGraphsMatch = h.match(/struct CudaGraphsConfig \{[^}]+\}/s);
  assert(cudaGraphsMatch, 'CudaGraphsConfig struct not found');
  assert(!cudaGraphsMatch[0].includes('capture_expert_ffn'),
    'capture_expert_ffn should not be in CudaGraphsConfig (const field)');
});

// 11. Source has parse/to_json functions
test('parse_config function present', () => {
  assert(cpp.includes('Config parse_config'), 'missing parse_config');
});

test('config_to_json function present', () => {
  assert(cpp.includes('config_to_json'), 'missing config_to_json');
});

// 12. Const fields emitted in to_json
test('capture_expert_ffn emitted as false in to_json', () => {
  assert(cpp.includes('capture_expert_ffn') && cpp.includes('false'),
    'capture_expert_ffn not emitted as const false in to_json');
});

// 13. x-internal fields in struct but NOT in parse/to_json
test('pcie_gen_max is in GpuConfig struct (x-internal)', () => {
  const gpuMatch = h.match(/struct GpuConfig \{[\s\S]+?\n\};/m);
  assert(gpuMatch, 'GpuConfig struct not found');
  assert(gpuMatch[0].includes('int pcie_gen_max'), 'pcie_gen_max missing from GpuConfig');
});

test('pcie_width_max is in GpuConfig struct (x-internal)', () => {
  const gpuMatch = h.match(/struct GpuConfig \{[\s\S]+?\n\};/m);
  assert(gpuMatch[0].includes('int pcie_width_max'), 'pcie_width_max missing from GpuConfig');
});

test('pci_bus_id is in GpuConfig struct (x-internal)', () => {
  const gpuMatch = h.match(/struct GpuConfig \{[\s\S]+?\n\};/m);
  assert(gpuMatch[0].includes('std::string pci_bus_id'), 'pci_bus_id missing from GpuConfig');
});

test('x-internal fields NOT parsed from JSON', () => {
  assert(!cpp.includes('pcie_gen_max'), 'pcie_gen_max should not appear in parser');
  assert(!cpp.includes('pcie_width_max'), 'pcie_width_max should not appear in parser');
  assert(!cpp.includes('pci_bus_id'), 'pci_bus_id should not appear in parser');
});

// 14. Optional objects
test('rope_scaling is std::optional', () => {
  assert(h.includes('std::optional<RopeScalingConfig> rope_scaling'),
    'rope_scaling should be std::optional');
});

test('vision is std::optional', () => {
  assert(h.includes('std::optional<VisionConfig> vision'),
    'vision should be std::optional');
});

console.log(`\n=== Results: ${passed} passed, ${failed} failed ===`);
process.exit(failed > 0 ? 1 : 0);
