#pragma once

// AUTO-GENERATED by tools/gen_config.mjs — DO NOT EDIT

#include <cstdint>
#include <optional>
#include <string>
#include <variant>
#include <vector>

#include <nlohmann/json.hpp>

#include "core/parser_headers.h"

namespace layerstorm::config {

// ── Enums ────────────────────────────────────────────────────────────────────

enum class GpuRole { attention, resident, expert_streaming };
enum class RopeScalingType { yarn, default_scaling };
enum class Architecture { deepseek_v3, glm_moe_dsa, kimi_k25, deepseek_v4 };
enum class WeightsFormat { safetensors, gguf };
enum class GatingScoreFn { sigmoid, softmax, sqrtsoftplus };
enum class WeightQuant { nvfp4, fp8_e4m3, fp8_e5m2, int4_symmetric, int4_asymmetric, gguf, gguf_q2_k, gguf_q3_k, gguf_q4_k, gguf_q5_k, gguf_q6_k, gguf_q8_0, gguf_mxfp4 };
enum class GgufStrategy { int_strategy, dequant };
enum class AttentionQuant { fp8_e4m3, fp8_e5m2, fp16 };
enum class KvCacheQuant { fp8_e4m3, fp8_e5m2, fp16 };
enum class GatingQuant { fp32, fp16 };
enum class DcpIndexerMode { replicated, local };
enum class DcpKvMode { replicated, sharded };
enum class EvictionPolicy { impact_weighted_lru, lru, lfu };
enum class IoEngine { io_uring, libaio };
enum class NumaStrategy { affinity_based, round_robin };
enum class NumaFallback { round_robin, sequential };
enum class HostPoolSizingMode { fraction_free, fraction_total, absolute_gb };
enum class ArenaOnConflict { unset, new_arena, fail, kill };
enum class SpeculationMethodType { none, null, mtp, prompt_lookup, dspark };
enum class DsparkDraftWeightsQuant { bf16, fp8_e4m3, nvfp4 };
enum class DsparkHeadType { markov, gated, rnn };
enum class DsparkSchedulerMode { off, static_threshold, throughput };
enum class InFlightTransferMode { conservative, optimistic };
enum class RankingStrategy { router_based, static_calibration };
enum class SubstitutionPolicy { substitution, discard };
enum class LayerSkipMethod { cosine_similarity, clsap, static_exit };
enum class Strategy { cascade, ema, fixed };
enum class InitialAssignment { round_robin, coactivation };
enum class GemmBackend { cutlass };
enum class AttentionBackendType { snapmla, turboquant_mla, csa_hca, csa_hca_tq, csa_hca_tq_mix };
enum class DeterministicEpCombinePrecision { fp32, bf16 };
enum class HostCacheMode { mmap, explicit_alloc };
enum class CalibrationMode { loaded, quick, full };

// ── Special types ────────────────────────────────────────────────────────────

// "all" or a list of layer indices
using LayerPinSpec = std::variant<std::string, std::vector<int>>;

// "auto" or a positive integer
using AutoOrInt = std::variant<std::string, int>;

// ── Structs ──────────────────────────────────────────────────────────────────

struct VramAllocationConfig {
    double resident = 0.0;
    double expert_streaming = 0.0;
    double stable_zone_fraction = -1.0;
    double safety_margin_gb = -1.0;
};

struct GpuConfig {
    int id{};
    GpuType type{};
    double vram_gb = 0.0;
    int pcie_gen = 0;
    int pcie_width = 0;
    int numa_node = -1;
    double pcie_bandwidth_loss_ratio = 0.85;
    std::optional<double> compute_weight;
    int vram_budget_gb = 0;
    std::vector<GpuRole> roles = {GpuRole::attention, GpuRole::resident, GpuRole::expert_streaming};
    std::optional<VramAllocationConfig> vram_allocation_gb;
    GpuRef ref;
    int pcie_gen_max = 0;
    int pcie_width_max = 0;
    std::string pci_bus_id = "";
};

struct CpuExpertConfig {
    int numa_node{};
    int max_threads = 0;
    bool enabled = true;
};

struct RopeScalingConfig {
    RopeScalingType type{};
    std::optional<double> factor;
    std::optional<double> beta_fast;
    std::optional<double> beta_slow;
    std::optional<double> mscale;
    std::optional<double> mscale_all_dim;
    std::optional<double> original_max_position_embeddings;
};

struct VisionConfig {
    bool enabled = false;
    int hidden_size = 1152;
    int num_layers = 27;
    int num_heads = 16;
    int patch_size = 14;
    int image_size = 384;
};

struct ModelConfig {
    Architecture architecture{};
    std::string weights_path{};
    WeightsFormat weights_format{};
    bool use_mmap = true;
    int num_hidden_layers{};
    int hidden_size{};
    int num_attention_heads{};
    int num_key_value_heads{};
    int kv_lora_rank = 512;
    int qk_rope_head_dim = 64;
    int qk_nope_head_dim = 128;
    int v_head_dim = 128;
    int q_lora_rank = 1536;
    int intermediate_size{};
    int n_routed_experts{};
    int n_shared_experts = 1;
    int num_experts_per_tok{};
    int n_group = 8;
    int topk_group = 4;
    int vocab_size = 0;
    int max_position_embeddings{};
    double rope_theta = 10000.0;
    double rms_norm_eps = 0.000001;
    int num_nextn_predict_layers = 1;
    int index_topk = 2048;
    int index_n_heads = 64;
    int index_head_dim = 128;
    int index_topk_freq = 0;
    int index_skip_topk_offset = 0;
    std::optional<RopeScalingConfig> rope_scaling;
    bool rope_interleave = false;
    bool indexer_rope_interleave = false;
    int first_k_dense_replace = 3;
    double routed_scaling_factor = 2.5;
    int moe_intermediate_size = 2048;
    int moe_layer_freq = 1;
    bool norm_topk_prob = true;
    GatingScoreFn gating_score_fn = GatingScoreFn::sigmoid;
    int head_dim = 0;
    std::vector<int> compress_ratios = {};
    double compress_rope_theta = 0.0;
    int sliding_window = 0;
    double swiglu_limit = 0.0;
    int num_hash_layers = 0;
    int o_groups = 1;
    int o_lora_rank = 0;
    int hc_mult = 1;
    int hc_sinkhorn_iters = 20;
    double hc_eps = 0.000001;
    std::optional<VisionConfig> vision;
};

struct QuantizationConfig {
    WeightQuant weights = WeightQuant::nvfp4;
    GgufStrategy gguf_strategy = GgufStrategy::int_strategy;
    AttentionQuant attention_compute = AttentionQuant::fp8_e4m3;
    KvCacheQuant kv_cache = KvCacheQuant::fp8_e4m3;
    GatingQuant gating_compute = GatingQuant::fp32;
};

struct HardwareConfig {
    std::vector<GpuConfig> gpus{};
    std::vector<CpuExpertConfig> cpu_expert_devices = {};
    std::vector<int> tp_array = {};
    int system_ram_gb = 0;
    std::vector<std::string> nvme_paths = {};
    std::optional<int> nvme_capacity_gb;
    bool dcp_enabled = true;
    DcpIndexerMode dcp_indexer_mode = DcpIndexerMode::replicated;
    DcpKvMode dcp_kv_mode = DcpKvMode::sharded;
};

struct PinnedLayersConfig {
    LayerPinSpec attention = std::string{"all"};
    std::vector<int> dense_ffn_layers = {0, 1, 2, 59, 60};
    bool embedding = true;
    bool output_head = true;
    LayerPinSpec gating = std::string{"all"};
};

struct TpModePerLayerConfig {
    int default_mode = 0;
    int gating = 0;
    int pinned_dense_ffn = 0;
    int attention = 0;
    int shared_expert = 0;
    int embedding = 0;
    int output_head = 0;
};

struct KvCacheAdvancedConfig {
    double fragmentation_tolerance = 0.15;
};

struct KvCacheConfig {
    AutoOrInt max_pages_per_gpu = std::string{"auto"};
    int page_size_tokens = 16;
    double speculation_pool_fraction = 0.15;
    int indexer_k_page_size_tokens = 8192;
    double prefill_scratch_preallocated_gb = 0.5;
    double streaming_spill_fraction = 0.34;
    int dcp_chunk_size = 16;
    std::optional<int> naive_prefill_context_ceiling;
    int page_growth_chunk_tokens = 1024;
    KvCacheAdvancedConfig _advanced;
};

struct KvTieringConfig {
    bool enabled = false;
    int hot_buffer_slots = 0;
    double host_to_device_ratio = 8.0;
    bool replica_cold_dedup = true;
    bool tiered_prefill = false;
    int admission_window_tokens = 0;
};

struct ExpertCacheAdvancedConfig {
    double layer_depth_decay_factor = 0.95;
    bool entropy_aware_eviction = false;
};

struct ExpertCacheConfig {
    EvictionPolicy eviction_policy = EvictionPolicy::impact_weighted_lru;
    double eviction_alpha_recency = 0.4;
    double eviction_beta_frequency = 0.35;
    double eviction_gamma_routing_weight = 0.25;
    double eviction_delta_temporal_autocorr = 0.0;
    double eviction_epsilon_coactivation = 0.0;
    double eviction_zeta_prefetch_score = 0.0;
    double eviction_eta_hysteresis = 0.0;
    bool hysteresis_enabled = false;
    int hysteresis_stages = 5;
    int hysteresis_up_threshold = 5;
    int hysteresis_down_threshold = 1;
    int duplication_frequency_threshold_percentile = 95;
    double temporal_autocorrelation_bonus = 0.8;
    double stable_zone_fraction = 0.7;
    bool inclusive_cache = true;
    ExpertCacheAdvancedConfig _advanced;
};

struct NvmeTierConfig {
    bool enabled = false;
    IoEngine io_engine = IoEngine::io_uring;
    int queue_depth = 64;
    int prefetch_ahead_layers = 3;
    std::optional<double> host_ram_cache_gb;
    bool direct_io = true;
};

struct NumaConfig {
    NumaStrategy interleave_strategy = NumaStrategy::affinity_based;
    NumaFallback fallback = NumaFallback::round_robin;
};

struct PerNodeConfig {
    int node{};
    HostPoolSizingMode mode{};
    double value{};
};

struct PinHostExpertPoolSizingConfig {
    HostPoolSizingMode mode = HostPoolSizingMode::fraction_total;
    double value = 0.9;
    std::vector<PerNodeConfig> per_node = {};
};

struct NodesConfig {
    int node{};
    int weight{};
};

struct CrossNodeSpillConfig {
    bool enabled = true;
    std::vector<NodesConfig> nodes = {};
    HostPoolSizingMode sizing_mode = HostPoolSizingMode::fraction_total;
    double sizing_value = 0.9;
    std::vector<PerNodeConfig> per_node = {};
};

struct ArenaAttachConfig {
    bool enabled = true;
    std::string socket_path = "@layerstorm-arena";
    std::string holder_binary = "";
    bool auto_spawn = true;
    bool persist = false;
    ArenaOnConflict on_conflict = ArenaOnConflict::unset;
};

struct ArenaPlacementConfig {
    std::string freq_table = "";
    bool online = true;
};

struct MemoryConfig {
    PinnedLayersConfig pinned_layers;
    TpModePerLayerConfig tp_mode_per_layer;
    KvCacheConfig kv_cache;
    KvTieringConfig kv_tiering;
    ExpertCacheConfig expert_cache;
    NvmeTierConfig nvme_tier;
    NumaConfig numa;
    double vram_safety_margin_gb = 1.0;
    int host_packed_cache_mb = 0;
    bool preload_expert_buffers = true;
    bool pin_host_expert_pool = true;
    PinHostExpertPoolSizingConfig pin_host_expert_pool_sizing;
    int pin_host_expert_pool_extra_scratch_bytes = 0;
    bool pin_host_expert_pool_preload = true;
    CrossNodeSpillConfig cross_node_spill;
    std::optional<bool> pin_host_expert_pool_direct_load;
    bool pin_host_expert_pool_direct_o_direct = true;
    bool pin_host_expert_pool_iouring = false;
    bool pin_host_expert_pool_thp = true;
    ArenaAttachConfig arena_attach;
    ArenaPlacementConfig arena_placement;
};

struct PerformanceObjectiveConfig {
    double latency_weight = 0.6;
    double throughput_weight = 0.4;
};

struct ExpertBatchingConfig {
    bool enabled = true;
    int max_wait_us = 50;
    int min_batch_tokens_per_expert = 4;
};

struct CoactivationGraphConfig {
    bool enabled = true;
    double decay_factor = 0.999;
    int reoptimize_interval_seconds = 300;
    double workload_shift_decay = 0.1;
};

struct WorkloadDetectionAdvancedConfig {
    int token_window_size = 32;
};

struct WorkloadDetectionConfig {
    double ewma_alpha = 0.01;
    double shift_threshold_std_devs = 3.0;
    WorkloadDetectionAdvancedConfig _advanced;
};

struct IpcTransactionConfig {
    int writer_yield_interval = 16;
    int publish_interval_us = 5000;
    int reader_max_retries = 200000000;
    int reader_backoff_stage_size = 4096;
    int reader_stage0_yield_every = 64;
};

struct OrchestratorConfig {
    PerformanceObjectiveConfig performance_objective;
    int max_batch_size = 64;
    ExpertBatchingConfig expert_batching;
    CoactivationGraphConfig coactivation_graph;
    WorkloadDetectionConfig workload_detection;
    IpcTransactionConfig ipc_transaction;
};

struct PrescopeConfig {
    bool enabled = true;
    int lookahead_layers = 1;
    int top_k = 8;
    double score_threshold = 0.01;
    bool predictor_enabled = false;
};

struct ProbeConfig {
    bool enabled = true;
    std::vector<double> probe_points = {0.25, 0.5, 0.75};
    double confidence_threshold = 0.6;
};

struct MoeSpeqConfig {
    bool enabled = true;
    int predictor_hidden_size = 256;
    double learning_rate = 0.0001;
    int training_buffer_size = 10000;
    int train_interval_steps = 100;
};

struct SpeculativeConfig {
    bool enabled = true;
    int max_prefetch_depth_layers = 3;
    double confidence_threshold = 0.4;
};

struct FusionWeightsConfig {
    double prescope_alpha = 0.5;
    double probe_beta = 0.3;
    double speq_gamma = 0.2;
    double sp_moe_delta = 0.15;
};

struct PrefetchConfig {
    PrescopeConfig prescope;
    ProbeConfig probe;
    MoeSpeqConfig moe_speq;
    SpeculativeConfig speculative;
    FusionWeightsConfig fusion_weights;
};

struct MtpConfig {
    bool enabled = true;
    int max_depth = 3;
    bool dynamic_depth = true;
    double confidence_threshold = 0.4;
    bool batched_verify = true;
};

struct DsparkConfig {
    int block_size = 8;
    int speculative_tokens = 7;
    std::vector<int> aux_hidden_state_layer_ids = {8, 23, 39, 55, 70};
    int mask_token_id = 154856;
    int max_anchors = 1024;
    int draft_vocab_size = 154880;
    std::string checkpoint_path = "test-data/GLM-5.2-speculator.dspark";
    std::vector<int> draft_gpus = {};
    DsparkDraftWeightsQuant draft_weights_quant = DsparkDraftWeightsQuant::bf16;
    int markov_rank = 256;
    DsparkHeadType head_type = DsparkHeadType::markov;
    bool confidence_enabled = false;
    DsparkSchedulerMode scheduler_mode = DsparkSchedulerMode::off;
    double confidence_threshold = 0.5;
    std::vector<double> sts_temperatures = {};
    int draft_context_capacity_tokens = 8192;
    int aux_capture_max_rows = 2048;
    std::string epm_dump_dir = "";
    bool verify_chunk_prefetch = false;
};

struct ResidualCorrectionConfig {
    bool enabled = true;
    int hidden_size = 128;
    double learning_rate = 0.00005;
    int training_buffer_size = 50000;
};

struct SelfSpeculativeConfig {
    bool enabled = true;
    int draft_expert_count = 1;
    bool adaptive_exit_enabled = true;
    double draft_confidence_threshold = 0.4;
    ResidualCorrectionConfig residual_correction;
};

struct PromptLookupConfig {
    bool enabled = true;
    int min_ngram_size = 2;
    int max_ngram_size = 4;
    int max_continuation_length = 5;
};

struct VerificationAdvancedConfig {
    int max_draft_tree_size = 64;
};

struct VerificationConfig {
    double moe_spec_max_loaded_experts_fraction = 0.8;
    double adaptive_topk_threshold = 0.92;
    double verification_quality_floor = 0.85;
    InFlightTransferMode in_flight_transfer_mode = InFlightTransferMode::conservative;
    bool sparse_verification = false;
    RankingStrategy ranking_strategy = RankingStrategy::router_based;
    SubstitutionPolicy substitution_policy = SubstitutionPolicy::substitution;
    VerificationAdvancedConfig _advanced;
};

struct LayerSkipDraftAdvancedConfig {
    int layer_optimization_interval = 128;
    double decaying_threshold_temperature = 0.0;
};

struct LayerSkipDraftConfig {
    bool enabled = false;
    LayerSkipMethod method = LayerSkipMethod::cosine_similarity;
    double threshold = 0.995;
    double min_acceptance_rate_to_enable = 0.5;
    std::optional<int> exit_layer;
    double target_skip_fraction = 0.5;
    int no_skip_first = 3;
    int no_skip_last = 3;
    int min_contiguous = 1;
    int product_window = 1;
    double product_threshold = 0.985;
    LayerSkipDraftAdvancedConfig _advanced;
};

struct TransferCancellationConfig {
    bool cancel_abort_transfers = true;
    bool cancel_skip_transfers = true;
    int cancel_stability_window = 2;
    int transfer_origin_expiry_cycles = 10000;
};

struct ReasoningModeConfig {
    bool enabled = false;
    bool think_token_detection = true;
    double aggressive_speculation_depth_multiplier = 2.0;
    double relaxed_verification_threshold = 0.85;
};

struct CalibrationAdvancedConfig {
    int cascade_test_iterations = 4;
    int cascade_set_iterations = 16;
    bool cascade_adaptive_backoff = true;
};

struct CalibrationConfig {
    double min_acceptance_rate = 0.3;
    double target_acceptance_rate = 0.6;
    int adjustment_interval_tokens = 500;
    double acceptance_ema_alpha = 0.5;
    double draft_count_ema_alpha = 0.9;
    double adjustment_step_size = 0.01;
    CalibrationAdvancedConfig _advanced;
};

struct UtilityScorerConfig {
    bool enabled = true;
    Strategy strategy = Strategy::cascade;
    int static_depth = 3;
    double utility_threshold = 1.0;
    double vram_headroom_fraction = 0.1;
};

struct DraftCombinerConfig {
    bool enabled = true;
    double prompt_lookup_priority_boost = 1.0;
    double mtp_compute_cost = 0.1;
    double self_spec_compute_cost = 0.5;
    double dspark_compute_cost = 0.05;
};

struct SpeculationConfig {
    bool enabled = true;
    SpeculationMethodType method = SpeculationMethodType::none;
    MtpConfig mtp;
    DsparkConfig dspark;
    SelfSpeculativeConfig self_speculative;
    PromptLookupConfig prompt_lookup;
    VerificationConfig verification;
    LayerSkipDraftConfig layer_skip_draft;
    TransferCancellationConfig transfer_cancellation;
    ReasoningModeConfig reasoning_mode;
    CalibrationConfig calibration;
    UtilityScorerConfig utility_scorer;
    DraftCombinerConfig draft_combiner;
};

struct ExpertAffinityConfig {
    InitialAssignment initial_assignment = InitialAssignment::round_robin;
    int rebalance_interval_seconds = 300;
};

struct ExpertDuplicationConfig {
    bool enabled = true;
    double max_duplicated_fraction = 0.05;
};

struct NodeRoutingConfig {
    int max_nodes_per_token = 4;
};

struct ParallelismConfig {
    int tensor_parallelism = 2;
    ExpertAffinityConfig expert_affinity;
    ExpertDuplicationConfig expert_duplication;
    NodeRoutingConfig node_routing;
};

struct FineGrainedConfig {
    bool enabled = false;
    int max_in_flight_per_gpu = 4;
    int prefetch_distance_layers = 4;
};

struct TransferConfig {
    FineGrainedConfig fine_grained;
    int streams_per_gpu = 2;
    int priority_levels = 3;
};

struct CudaGraphsConfig {
    bool enabled = true;
    bool capture_attention = true;
    bool capture_gating = true;
    bool capture_tp_allreduce = true;
};

struct GemmConfig {
    GemmBackend backend = GemmBackend::cutlass;
    bool grouped_gemm = true;
    bool fused_swiglu = true;
};

struct ComputeConfig {
    CudaGraphsConfig cuda_graphs;
    GemmConfig gemm;
    AttentionBackendType attention_backend = AttentionBackendType::snapmla;
    int prefill_superchunk_tokens = 0;
    bool prefill_moe_big = true;
    int moe_big_chunk_tokens = 512;
    bool dsa_sparse_prefill = false;
    bool dsa_indexer_rewind = true;
    bool deterministic_reduce = true;
    bool deterministic_ep_combine = false;
    DeterministicEpCombinePrecision deterministic_ep_combine_precision = DeterministicEpCombinePrecision::bf16;
    bool ipc_pin = true;
};

struct PrefixCacheConfig {
    bool enabled = true;
    int max_cached_tokens = 8192;
    int max_entries = 8;
};

struct ServingConfig {
    std::string host = "0.0.0.0";
    int port = 8000;
    int max_concurrent_requests = 32;
    int max_queued_requests = 16;
    int max_sequence_length = 32768;
    std::string tokenizer_path = "auto";
    std::string tool_call_parser = "";
    bool enable_auto_tool_choice = false;
    std::string reasoning_parser = "";
    std::string reasoning_config = "";
    std::string tokenizer_mode = "auto";
    PrefixCacheConfig prefix_cache;
};

struct PreprocessingConfig {
    std::string prepacked_dir = "";
    bool auto_preprocess = false;
    std::string auto_preprocess_target = "";
    HostCacheMode host_cache_mode = HostCacheMode::mmap;
    bool legacy_weights = false;
};

struct PrescopeInternalConfig {
    int hidden_size = 7168;
    int pca_dim = 256;
    int hidden_dim = 256;
    double learning_rate = 0.001;
    double momentum = 0.9;
    int training_batch_size = 32;
    int training_buffer_size = 2048;
    double focal_loss_gamma = 2.0;
    double balance_loss_lambda = 0.5;
    double input_group_frac = 0.25;
    double output_group_frac = 0.25;
    int min_samples_before_predict = 64;
    double freq_ema_alpha = 0.01;
};

struct ResidualCorrectionInternalConfig {
    int training_batch_size = 32;
    int min_samples_before_predict = 64;
    double beta1 = 0.9;
    double beta2 = 0.999;
    double epsilon = 1e-8;
};

struct UtilityScorerInternalConfig {
    std::vector<int> candidate_depths = {0, 1, 2, 3, 5, 7};
    int test_iterations = 4;
    int set_iterations = 16;
    double convergence_tolerance = 0.1;
    int backoff_multiplier = 2;
    double ema_alpha = 0.3;
    double ema_up_threshold = 0.0;
    double ema_down_threshold = -0.25;
    double coverage_discount_floor = 0.5;
};

struct MtpDraftInternalConfig {
    double confidence_threshold = 0.4;
    double acceptance_ema_alpha = 0.3;
};

struct PromptLookupInternalConfig {
    double acceptance_ema_alpha = 0.3;
};

struct SelfSpeculativeInternalConfig {
    int max_depth = 5;
    double acceptance_ema_alpha = 0.3;
};

struct ProbeInternalConfig {
    int hidden_size = 7168;
    int feature_dim = 256;
    double learning_rate = 0.001;
    double momentum = 0.9;
    int training_batch_size = 32;
    int training_buffer_size = 2048;
    int min_samples_before_predict = 64;
};

struct MoeSpeqInternalConfig {
    int hidden_size = 7168;
    int feature_dim = 256;
    double beta1 = 0.9;
    double beta2 = 0.999;
    double epsilon = 1e-8;
    int training_batch_size = 32;
    int min_samples_before_predict = 64;
};

struct SpeculativePrefetchInternalConfig {
    double per_layer_us = 920.0;
    double pcie_bw_bytes_per_us = 64000.0;
    int max_transfers_per_plan = 256;
};

struct PrefetchFuserInternalConfig {
    double prescope_alpha = 0.5;
    double probe_beta = 0.3;
    double speq_gamma = 0.2;
    double sp_moe_delta = 0.15;
    double time_decay = 0.1;
    double per_layer_us = 920.0;
};

struct SchedulerInternalConfig {
    double urgency_weight = 0.4;
    double readiness_weight = 0.4;
    double batching_weight = 0.2;
    int max_batch_size = 64;
    double speculation_penalty = 0.1;
};

struct GpuLoadBalancerInternalConfig {
    double weight_residency = 0.25;
    double weight_capacity = 0.2;
    double weight_headroom = 0.1;
    double weight_affinity = 0.15;
    double weight_transfer_cost = 0.15;
    double weight_cache_quality_stable = 0.1;
    double weight_cache_quality_streaming = 0.05;
    std::vector<double> priority_bin_thresholds = {0.3, 0.7};
    bool learned_scorer_enabled = false;
    int learned_scorer_hidden_size = 32;
    double learned_scorer_learning_rate = 0.0001;
    int learned_scorer_buffer_size = 10000;
    int learned_scorer_min_samples = 128;
};

struct DraftCombinerInternalConfig {
    double acceptance_ema_alpha = 0.3;
    double latency_per_position_us = 920.0;
    double min_utility_threshold = 0.0;
    double coverage_discount_floor = 0.5;
};

struct VerifierInternalConfig {
    double acceptance_ema_alpha = 0.3;
};

struct DsparkInternalConfig {
    double acceptance_ema_alpha = 0.3;
    int confidence_trace_capacity = 4096;
};

struct OrchestratorInternalConfig {
    std::vector<int> ep_gpu_indices = {};
};

struct GpuLoaderConfig {
    bool enabled = false;
    CalibrationMode calibration_mode = CalibrationMode::loaded;
    std::string calibration_path = "";
};

struct Config {
    std::optional<std::string> preset;
    ModelConfig model{};
    QuantizationConfig quantization{};
    HardwareConfig hardware{};
    MemoryConfig memory;
    OrchestratorConfig orchestrator;
    PrefetchConfig prefetch;
    SpeculationConfig speculation;
    ParallelismConfig parallelism;
    TransferConfig transfer;
    ComputeConfig compute;
    ServingConfig serving;
    PreprocessingConfig preprocessing;
    PrescopeInternalConfig _internal_prescope;
    ResidualCorrectionInternalConfig _internal_residual_correction;
    UtilityScorerInternalConfig _internal_utility_scorer;
    MtpDraftInternalConfig _internal_mtp_draft;
    PromptLookupInternalConfig _internal_prompt_lookup;
    SelfSpeculativeInternalConfig _internal_self_speculative;
    ProbeInternalConfig _internal_probe;
    MoeSpeqInternalConfig _internal_moe_speq;
    SpeculativePrefetchInternalConfig _internal_speculative_prefetch;
    PrefetchFuserInternalConfig _internal_prefetch_fuser;
    SchedulerInternalConfig _internal_scheduler;
    GpuLoadBalancerInternalConfig _internal_gpu_load_balancer;
    DraftCombinerInternalConfig _internal_draft_combiner;
    VerifierInternalConfig _internal_verifier;
    DsparkInternalConfig _internal_dspark;
    OrchestratorInternalConfig _internal_orchestrator;
    GpuLoaderConfig gpu_loader;
};

// ── FieldId ──────────────────────────────────────────────────────────────────

enum class FieldId : uint16_t {
    kPreset = 0,
    kModelArchitecture = 1,
    kModelWeightsPath = 2,
    kModelWeightsFormat = 3,
    kModelUseMmap = 4,
    kModelNumHiddenLayers = 5,
    kModelHiddenSize = 6,
    kModelNumAttentionHeads = 7,
    kModelNumKeyValueHeads = 8,
    kModelKvLoraRank = 9,
    kModelQkRopeHeadDim = 10,
    kModelQkNopeHeadDim = 11,
    kModelVHeadDim = 12,
    kModelQLoraRank = 13,
    kModelIntermediateSize = 14,
    kModelNRoutedExperts = 15,
    kModelNSharedExperts = 16,
    kModelNumExpertsPerTok = 17,
    kModelNGroup = 18,
    kModelTopkGroup = 19,
    kModelVocabSize = 20,
    kModelMaxPositionEmbeddings = 21,
    kModelRopeTheta = 22,
    kModelRmsNormEps = 23,
    kModelNumNextnPredictLayers = 24,
    kModelIndexTopk = 25,
    kModelIndexNHeads = 26,
    kModelIndexHeadDim = 27,
    kModelIndexTopkFreq = 28,
    kModelIndexSkipTopkOffset = 29,
    kModelRopeScalingType = 30,
    kModelRopeScalingFactor = 31,
    kModelRopeScalingBetaFast = 32,
    kModelRopeScalingBetaSlow = 33,
    kModelRopeScalingMscale = 34,
    kModelRopeScalingMscaleAllDim = 35,
    kModelRopeScalingOriginalMaxPositionEmbeddings = 36,
    kModelRopeInterleave = 37,
    kModelIndexerRopeInterleave = 38,
    kModelFirstKDenseReplace = 39,
    kModelRoutedScalingFactor = 40,
    kModelMoeIntermediateSize = 41,
    kModelMoeLayerFreq = 42,
    kModelNormTopkProb = 43,
    kModelGatingScoreFn = 44,
    kModelHeadDim = 45,
    kModelCompressRopeTheta = 46,
    kModelSlidingWindow = 47,
    kModelSwigluLimit = 48,
    kModelNumHashLayers = 49,
    kModelOGroups = 50,
    kModelOLoraRank = 51,
    kModelHcMult = 52,
    kModelHcSinkhornIters = 53,
    kModelHcEps = 54,
    kModelVisionEnabled = 55,
    kModelVisionHiddenSize = 56,
    kModelVisionNumLayers = 57,
    kModelVisionNumHeads = 58,
    kModelVisionPatchSize = 59,
    kModelVisionImageSize = 60,
    kQuantizationWeights = 61,
    kQuantizationGgufStrategy = 62,
    kQuantizationAttentionCompute = 63,
    kQuantizationKvCache = 64,
    kQuantizationGatingCompute = 65,
    kHardwareSystemRamGb = 66,
    kHardwareNvmeCapacityGb = 67,
    kHardwareDcpIndexerMode = 68,
    kHardwareDcpKvMode = 69,
    kMemoryPinnedLayersAttention = 70,
    kMemoryPinnedLayersEmbedding = 71,
    kMemoryPinnedLayersOutputHead = 72,
    kMemoryPinnedLayersGating = 73,
    kMemoryTpModePerLayerDefaultMode = 74,
    kMemoryTpModePerLayerGating = 75,
    kMemoryTpModePerLayerPinnedDenseFfn = 76,
    kMemoryTpModePerLayerAttention = 77,
    kMemoryTpModePerLayerSharedExpert = 78,
    kMemoryTpModePerLayerEmbedding = 79,
    kMemoryTpModePerLayerOutputHead = 80,
    kMemoryKvCacheMaxPagesPerGpu = 81,
    kMemoryKvCachePageSizeTokens = 82,
    kMemoryKvCacheSpeculationPoolFraction = 83,
    kMemoryKvCacheIndexerKPageSizeTokens = 84,
    kMemoryKvCachePrefillScratchPreallocatedGb = 85,
    kMemoryKvCacheStreamingSpillFraction = 86,
    kMemoryKvCacheDcpChunkSize = 87,
    kMemoryKvCacheNaivePrefillContextCeiling = 88,
    kMemoryKvCachePageGrowthChunkTokens = 89,
    kMemoryKvCacheAdvancedFragmentationTolerance = 90,
    kMemoryKvTieringEnabled = 91,
    kMemoryKvTieringHotBufferSlots = 92,
    kMemoryKvTieringHostToDeviceRatio = 93,
    kMemoryKvTieringReplicaColdDedup = 94,
    kMemoryKvTieringTieredPrefill = 95,
    kMemoryKvTieringAdmissionWindowTokens = 96,
    kMemoryExpertCacheEvictionPolicy = 97,
    kMemoryExpertCacheEvictionAlphaRecency = 98,
    kMemoryExpertCacheEvictionBetaFrequency = 99,
    kMemoryExpertCacheEvictionGammaRoutingWeight = 100,
    kMemoryExpertCacheEvictionDeltaTemporalAutocorr = 101,
    kMemoryExpertCacheEvictionEpsilonCoactivation = 102,
    kMemoryExpertCacheEvictionZetaPrefetchScore = 103,
    kMemoryExpertCacheEvictionEtaHysteresis = 104,
    kMemoryExpertCacheHysteresisEnabled = 105,
    kMemoryExpertCacheHysteresisStages = 106,
    kMemoryExpertCacheHysteresisUpThreshold = 107,
    kMemoryExpertCacheHysteresisDownThreshold = 108,
    kMemoryExpertCacheDuplicationFrequencyThresholdPercentile = 109,
    kMemoryExpertCacheTemporalAutocorrelationBonus = 110,
    kMemoryExpertCacheStableZoneFraction = 111,
    kMemoryExpertCacheInclusiveCache = 112,
    kMemoryExpertCacheAdvancedLayerDepthDecayFactor = 113,
    kMemoryExpertCacheAdvancedEntropyAwareEviction = 114,
    kMemoryNvmeTierEnabled = 115,
    kMemoryNvmeTierIoEngine = 116,
    kMemoryNvmeTierQueueDepth = 117,
    kMemoryNvmeTierPrefetchAheadLayers = 118,
    kMemoryNvmeTierHostRamCacheGb = 119,
    kMemoryNvmeTierDirectIo = 120,
    kMemoryNumaInterleaveStrategy = 121,
    kMemoryNumaFallback = 122,
    kMemoryVramSafetyMarginGb = 123,
    kMemoryHostPackedCacheMb = 124,
    kMemoryPreloadExpertBuffers = 125,
    kMemoryPinHostExpertPool = 126,
    kMemoryPinHostExpertPoolSizingMode = 127,
    kMemoryPinHostExpertPoolSizingValue = 128,
    kMemoryPinHostExpertPoolExtraScratchBytes = 129,
    kMemoryPinHostExpertPoolPreload = 130,
    kMemoryCrossNodeSpillEnabled = 131,
    kMemoryCrossNodeSpillSizingMode = 132,
    kMemoryCrossNodeSpillSizingValue = 133,
    kMemoryPinHostExpertPoolDirectLoad = 134,
    kMemoryPinHostExpertPoolDirectODirect = 135,
    kMemoryPinHostExpertPoolIouring = 136,
    kMemoryPinHostExpertPoolThp = 137,
    kMemoryArenaAttachEnabled = 138,
    kMemoryArenaAttachSocketPath = 139,
    kMemoryArenaAttachHolderBinary = 140,
    kMemoryArenaAttachAutoSpawn = 141,
    kMemoryArenaAttachPersist = 142,
    kMemoryArenaAttachOnConflict = 143,
    kMemoryArenaPlacementFreqTable = 144,
    kMemoryArenaPlacementOnline = 145,
    kOrchestratorPerformanceObjectiveLatencyWeight = 146,
    kOrchestratorPerformanceObjectiveThroughputWeight = 147,
    kOrchestratorMaxBatchSize = 148,
    kOrchestratorExpertBatchingEnabled = 149,
    kOrchestratorExpertBatchingMaxWaitUs = 150,
    kOrchestratorExpertBatchingMinBatchTokensPerExpert = 151,
    kOrchestratorCoactivationGraphEnabled = 152,
    kOrchestratorCoactivationGraphDecayFactor = 153,
    kOrchestratorCoactivationGraphReoptimizeIntervalSeconds = 154,
    kOrchestratorCoactivationGraphWorkloadShiftDecay = 155,
    kOrchestratorWorkloadDetectionEwmaAlpha = 156,
    kOrchestratorWorkloadDetectionShiftThresholdStdDevs = 157,
    kOrchestratorWorkloadDetectionAdvancedTokenWindowSize = 158,
    kOrchestratorIpcTransactionWriterYieldInterval = 159,
    kOrchestratorIpcTransactionPublishIntervalUs = 160,
    kOrchestratorIpcTransactionReaderMaxRetries = 161,
    kOrchestratorIpcTransactionReaderBackoffStageSize = 162,
    kOrchestratorIpcTransactionReaderStage0YieldEvery = 163,
    kPrefetchPrescopeEnabled = 164,
    kPrefetchPrescopeLookaheadLayers = 165,
    kPrefetchPrescopeTopK = 166,
    kPrefetchPrescopeScoreThreshold = 167,
    kPrefetchPrescopePredictorEnabled = 168,
    kPrefetchProbeEnabled = 169,
    kPrefetchProbeConfidenceThreshold = 170,
    kPrefetchMoeSpeqEnabled = 171,
    kPrefetchMoeSpeqPredictorHiddenSize = 172,
    kPrefetchMoeSpeqLearningRate = 173,
    kPrefetchMoeSpeqTrainingBufferSize = 174,
    kPrefetchMoeSpeqTrainIntervalSteps = 175,
    kPrefetchSpeculativeEnabled = 176,
    kPrefetchSpeculativeMaxPrefetchDepthLayers = 177,
    kPrefetchSpeculativeConfidenceThreshold = 178,
    kPrefetchFusionWeightsPrescopeAlpha = 179,
    kPrefetchFusionWeightsProbeBeta = 180,
    kPrefetchFusionWeightsSpeqGamma = 181,
    kPrefetchFusionWeightsSpMoeDelta = 182,
    kSpeculationEnabled = 183,
    kSpeculationMethod = 184,
    kSpeculationMtpEnabled = 185,
    kSpeculationMtpMaxDepth = 186,
    kSpeculationMtpDynamicDepth = 187,
    kSpeculationMtpConfidenceThreshold = 188,
    kSpeculationMtpBatchedVerify = 189,
    kSpeculationDsparkBlockSize = 190,
    kSpeculationDsparkSpeculativeTokens = 191,
    kSpeculationDsparkMaskTokenId = 192,
    kSpeculationDsparkMaxAnchors = 193,
    kSpeculationDsparkDraftVocabSize = 194,
    kSpeculationDsparkCheckpointPath = 195,
    kSpeculationDsparkDraftWeightsQuant = 196,
    kSpeculationDsparkMarkovRank = 197,
    kSpeculationDsparkHeadType = 198,
    kSpeculationDsparkConfidenceEnabled = 199,
    kSpeculationDsparkSchedulerMode = 200,
    kSpeculationDsparkConfidenceThreshold = 201,
    kSpeculationDsparkDraftContextCapacityTokens = 202,
    kSpeculationDsparkAuxCaptureMaxRows = 203,
    kSpeculationDsparkEpmDumpDir = 204,
    kSpeculationDsparkVerifyChunkPrefetch = 205,
    kSpeculationSelfSpeculativeEnabled = 206,
    kSpeculationSelfSpeculativeDraftExpertCount = 207,
    kSpeculationSelfSpeculativeAdaptiveExitEnabled = 208,
    kSpeculationSelfSpeculativeDraftConfidenceThreshold = 209,
    kSpeculationSelfSpeculativeResidualCorrectionEnabled = 210,
    kSpeculationSelfSpeculativeResidualCorrectionHiddenSize = 211,
    kSpeculationSelfSpeculativeResidualCorrectionLearningRate = 212,
    kSpeculationSelfSpeculativeResidualCorrectionTrainingBufferSize = 213,
    kSpeculationPromptLookupEnabled = 214,
    kSpeculationPromptLookupMinNgramSize = 215,
    kSpeculationPromptLookupMaxNgramSize = 216,
    kSpeculationPromptLookupMaxContinuationLength = 217,
    kSpeculationVerificationMoeSpecMaxLoadedExpertsFraction = 218,
    kSpeculationVerificationAdaptiveTopkThreshold = 219,
    kSpeculationVerificationVerificationQualityFloor = 220,
    kSpeculationVerificationInFlightTransferMode = 221,
    kSpeculationVerificationSparseVerification = 222,
    kSpeculationVerificationRankingStrategy = 223,
    kSpeculationVerificationSubstitutionPolicy = 224,
    kSpeculationVerificationAdvancedMaxDraftTreeSize = 225,
    kSpeculationLayerSkipDraftEnabled = 226,
    kSpeculationLayerSkipDraftMethod = 227,
    kSpeculationLayerSkipDraftThreshold = 228,
    kSpeculationLayerSkipDraftMinAcceptanceRateToEnable = 229,
    kSpeculationLayerSkipDraftExitLayer = 230,
    kSpeculationLayerSkipDraftTargetSkipFraction = 231,
    kSpeculationLayerSkipDraftNoSkipFirst = 232,
    kSpeculationLayerSkipDraftNoSkipLast = 233,
    kSpeculationLayerSkipDraftMinContiguous = 234,
    kSpeculationLayerSkipDraftProductWindow = 235,
    kSpeculationLayerSkipDraftProductThreshold = 236,
    kSpeculationLayerSkipDraftAdvancedLayerOptimizationInterval = 237,
    kSpeculationLayerSkipDraftAdvancedDecayingThresholdTemperature = 238,
    kSpeculationTransferCancellationCancelAbortTransfers = 239,
    kSpeculationTransferCancellationCancelSkipTransfers = 240,
    kSpeculationTransferCancellationCancelStabilityWindow = 241,
    kSpeculationTransferCancellationTransferOriginExpiryCycles = 242,
    kSpeculationReasoningModeEnabled = 243,
    kSpeculationReasoningModeThinkTokenDetection = 244,
    kSpeculationReasoningModeAggressiveSpeculationDepthMultiplier = 245,
    kSpeculationReasoningModeRelaxedVerificationThreshold = 246,
    kSpeculationCalibrationMinAcceptanceRate = 247,
    kSpeculationCalibrationTargetAcceptanceRate = 248,
    kSpeculationCalibrationAdjustmentIntervalTokens = 249,
    kSpeculationCalibrationAcceptanceEmaAlpha = 250,
    kSpeculationCalibrationDraftCountEmaAlpha = 251,
    kSpeculationCalibrationAdjustmentStepSize = 252,
    kSpeculationCalibrationAdvancedCascadeTestIterations = 253,
    kSpeculationCalibrationAdvancedCascadeSetIterations = 254,
    kSpeculationCalibrationAdvancedCascadeAdaptiveBackoff = 255,
    kSpeculationUtilityScorerEnabled = 256,
    kSpeculationUtilityScorerStrategy = 257,
    kSpeculationUtilityScorerStaticDepth = 258,
    kSpeculationUtilityScorerUtilityThreshold = 259,
    kSpeculationUtilityScorerVramHeadroomFraction = 260,
    kSpeculationDraftCombinerEnabled = 261,
    kSpeculationDraftCombinerPromptLookupPriorityBoost = 262,
    kSpeculationDraftCombinerMtpComputeCost = 263,
    kSpeculationDraftCombinerSelfSpecComputeCost = 264,
    kSpeculationDraftCombinerDsparkComputeCost = 265,
    kParallelismTensorParallelism = 266,
    kParallelismExpertAffinityInitialAssignment = 267,
    kParallelismExpertAffinityRebalanceIntervalSeconds = 268,
    kParallelismExpertDuplicationEnabled = 269,
    kParallelismExpertDuplicationMaxDuplicatedFraction = 270,
    kParallelismNodeRoutingMaxNodesPerToken = 271,
    kTransferFineGrainedEnabled = 272,
    kTransferFineGrainedMaxInFlightPerGpu = 273,
    kTransferFineGrainedPrefetchDistanceLayers = 274,
    kTransferStreamsPerGpu = 275,
    kTransferPriorityLevels = 276,
    kComputeCudaGraphsEnabled = 277,
    kComputeCudaGraphsCaptureAttention = 278,
    kComputeCudaGraphsCaptureGating = 279,
    kComputeCudaGraphsCaptureTpAllreduce = 280,
    kComputeGemmBackend = 281,
    kComputeGemmGroupedGemm = 282,
    kComputeGemmFusedSwiglu = 283,
    kComputeAttentionBackend = 284,
    kComputePrefillSuperchunkTokens = 285,
    kComputePrefillMoeBig = 286,
    kComputeMoeBigChunkTokens = 287,
    kComputeDsaSparsePrefill = 288,
    kComputeDsaIndexerRewind = 289,
    kComputeDeterministicReduce = 290,
    kComputeDeterministicEpCombine = 291,
    kComputeDeterministicEpCombinePrecision = 292,
    kComputeIpcPin = 293,
    kServingHost = 294,
    kServingPort = 295,
    kServingMaxConcurrentRequests = 296,
    kServingMaxQueuedRequests = 297,
    kServingMaxSequenceLength = 298,
    kServingTokenizerPath = 299,
    kServingToolCallParser = 300,
    kServingEnableAutoToolChoice = 301,
    kServingReasoningParser = 302,
    kServingReasoningConfig = 303,
    kServingTokenizerMode = 304,
    kServingPrefixCacheEnabled = 305,
    kServingPrefixCacheMaxCachedTokens = 306,
    kServingPrefixCacheMaxEntries = 307,
    kPreprocessingPrepackedDir = 308,
    kPreprocessingAutoPreprocess = 309,
    kPreprocessingAutoPreprocessTarget = 310,
    kPreprocessingHostCacheMode = 311,
    kPreprocessingLegacyWeights = 312,
    kInternalPrescopeHiddenSize = 313,
    kInternalPrescopePcaDim = 314,
    kInternalPrescopeHiddenDim = 315,
    kInternalPrescopeLearningRate = 316,
    kInternalPrescopeMomentum = 317,
    kInternalPrescopeTrainingBatchSize = 318,
    kInternalPrescopeTrainingBufferSize = 319,
    kInternalPrescopeFocalLossGamma = 320,
    kInternalPrescopeBalanceLossLambda = 321,
    kInternalPrescopeInputGroupFrac = 322,
    kInternalPrescopeOutputGroupFrac = 323,
    kInternalPrescopeMinSamplesBeforePredict = 324,
    kInternalPrescopeFreqEmaAlpha = 325,
    kInternalResidualCorrectionTrainingBatchSize = 326,
    kInternalResidualCorrectionMinSamplesBeforePredict = 327,
    kInternalResidualCorrectionBeta1 = 328,
    kInternalResidualCorrectionBeta2 = 329,
    kInternalResidualCorrectionEpsilon = 330,
    kInternalUtilityScorerTestIterations = 331,
    kInternalUtilityScorerSetIterations = 332,
    kInternalUtilityScorerConvergenceTolerance = 333,
    kInternalUtilityScorerBackoffMultiplier = 334,
    kInternalUtilityScorerEmaAlpha = 335,
    kInternalUtilityScorerEmaUpThreshold = 336,
    kInternalUtilityScorerEmaDownThreshold = 337,
    kInternalUtilityScorerCoverageDiscountFloor = 338,
    kInternalMtpDraftConfidenceThreshold = 339,
    kInternalMtpDraftAcceptanceEmaAlpha = 340,
    kInternalPromptLookupAcceptanceEmaAlpha = 341,
    kInternalSelfSpeculativeMaxDepth = 342,
    kInternalSelfSpeculativeAcceptanceEmaAlpha = 343,
    kInternalProbeHiddenSize = 344,
    kInternalProbeFeatureDim = 345,
    kInternalProbeLearningRate = 346,
    kInternalProbeMomentum = 347,
    kInternalProbeTrainingBatchSize = 348,
    kInternalProbeTrainingBufferSize = 349,
    kInternalProbeMinSamplesBeforePredict = 350,
    kInternalMoeSpeqHiddenSize = 351,
    kInternalMoeSpeqFeatureDim = 352,
    kInternalMoeSpeqBeta1 = 353,
    kInternalMoeSpeqBeta2 = 354,
    kInternalMoeSpeqEpsilon = 355,
    kInternalMoeSpeqTrainingBatchSize = 356,
    kInternalMoeSpeqMinSamplesBeforePredict = 357,
    kInternalSpeculativePrefetchPerLayerUs = 358,
    kInternalSpeculativePrefetchPcieBwBytesPerUs = 359,
    kInternalSpeculativePrefetchMaxTransfersPerPlan = 360,
    kInternalPrefetchFuserPrescopeAlpha = 361,
    kInternalPrefetchFuserProbeBeta = 362,
    kInternalPrefetchFuserSpeqGamma = 363,
    kInternalPrefetchFuserSpMoeDelta = 364,
    kInternalPrefetchFuserTimeDecay = 365,
    kInternalPrefetchFuserPerLayerUs = 366,
    kInternalSchedulerUrgencyWeight = 367,
    kInternalSchedulerReadinessWeight = 368,
    kInternalSchedulerBatchingWeight = 369,
    kInternalSchedulerMaxBatchSize = 370,
    kInternalSchedulerSpeculationPenalty = 371,
    kInternalGpuLoadBalancerWeightResidency = 372,
    kInternalGpuLoadBalancerWeightCapacity = 373,
    kInternalGpuLoadBalancerWeightHeadroom = 374,
    kInternalGpuLoadBalancerWeightAffinity = 375,
    kInternalGpuLoadBalancerWeightTransferCost = 376,
    kInternalGpuLoadBalancerWeightCacheQualityStable = 377,
    kInternalGpuLoadBalancerWeightCacheQualityStreaming = 378,
    kInternalGpuLoadBalancerLearnedScorerEnabled = 379,
    kInternalGpuLoadBalancerLearnedScorerHiddenSize = 380,
    kInternalGpuLoadBalancerLearnedScorerLearningRate = 381,
    kInternalGpuLoadBalancerLearnedScorerBufferSize = 382,
    kInternalGpuLoadBalancerLearnedScorerMinSamples = 383,
    kInternalDraftCombinerAcceptanceEmaAlpha = 384,
    kInternalDraftCombinerLatencyPerPositionUs = 385,
    kInternalDraftCombinerMinUtilityThreshold = 386,
    kInternalDraftCombinerCoverageDiscountFloor = 387,
    kInternalVerifierAcceptanceEmaAlpha = 388,
    kInternalDsparkAcceptanceEmaAlpha = 389,
    kInternalDsparkConfidenceTraceCapacity = 390,
    kGpuLoaderEnabled = 391,
    kGpuLoaderCalibrationMode = 392,
    kGpuLoaderCalibrationPath = 393,
    kFieldCount = 394
};

// ── Config file-linking ──────────────────────────────────────────────────────

struct ConfigFileLink {
    const char* section_key;
    const char* filename;
};

extern const ConfigFileLink kConfigFileLinks[];
extern const size_t kConfigFileLinkCount;

// ── API ──────────────────────────────────────────────────────────────────────

/// Parse a JSON config file into a strongly-typed Config struct.
/// Throws std::runtime_error on file I/O errors.
/// Throws nlohmann::json::exception on parse/type errors.
Config parse_config(const std::string& path);

/// Parse a JSON object into a Config struct.
Config parse_config(const nlohmann::json& j);

/// Serialize a Config back to JSON.
nlohmann::json config_to_json(const Config& cfg);

/// Returns true if the field can be changed at runtime without engine restart.
bool is_changeable(FieldId id);

/// Returns the dotted path name of a field (e.g. "prefetch.prescope.top_k").
const char* field_name(FieldId id);

/// Apply a single field update to the config. Returns true on success.
/// value_type: 0=bool, 1=int32, 2=float. raw_value is reinterpreted.
bool apply_field_update(Config& cfg, FieldId id, uint8_t value_type, uint32_t raw_value);

}  // namespace layerstorm::config
