// kda_kernels_test.cu — GF3.7: KDA (Kimi Delta Attention) SM120 kernels on GPU.
//
// ── What is under test ──────────────────────────────────────────────────────
// The five launch wrappers in src/compute/kernels/sm120/attention/kda_linear.h
// (kernels: deps/LayerStoRmKernels/csrc/sm120/linear/kda_scan.h):
//   launch_kda_conv_prefill / launch_kda_conv_decode  — width-4 depthwise
//       causal short conv on q/k/v with carried ring state (+ SiLU),
//   launch_kda_chunked_scan                           — chunk-64 WY/UT prefill
//       scan (safe gate, q/k L2 norm, delta rule, fp32 state in place),
//   launch_kda_gated_rmsnorm                          — o_norm for the prefill
//       path,
//   launch_kda_decode_step                            — fused O(1) decode step
//       (gate + norm + decay + delta + rank-1 write + output + o_norm).
//
// ── The specification is the CPU reference, not this file ───────────────────
// tests/unit/kda_reference.h (GF3.6) and the committed goldens under
// test-data/kda-goldens/ (generated by the INDEPENDENT NumPy transcription
// tools/gen_kda_golden.py) are the arbiter. Every GPU number below is judged
// against kda_ref::{conv_prefill, conv_step, recurrent_step, recurrent_scan,
// chunked_scan, gated_rmsnorm} on bit-identical inputs, or against the golden
// fixtures directly. Where the GPU is expected to be BITWISE equal to itself
// (chunk-64 state carry, conv ring carry, slot indirection) the tests assert
// memcmp equality — those are the properties GF3.8's state pool and GF3.12's
// checkpoints stand on, and a tolerance would hide their loss.
//
// ── Tolerance provenance ────────────────────────────────────────────────────
// The kernels build with --use_fast_math, so expf/sigmoid/rsqrtf/silu are the
// CUDA fast-math approximations while the reference calls libm; the chunked
// scan also reassociates the sums the recurrence does sequentially. Every
// comparison therefore uses the reference test's scale-aware band
// (|a-b| <= frac_scale*max|b| + frac_elem*|b|) and PRINTS the measured worst
// case as a "[kda-tol] <label> max_excess=... max_abs=..." line — on pass as
// well as on fail. The bands below are STARTING values carried over from the
// CPU reference test (GF3.6 measured probe); after the first real GPU run the
// [kda-tol] lines say exactly how much headroom each family has and the bands
// are to be tightened to ~10x the observed excess. Do not loosen a band
// without recording the measured number next to it.
//
// Geometry note: head_dim is compile-fixed at 128 in the kernels, so every
// KdaParams here uses head_dim = 128 and only num_heads varies.

#include "compute/kernels/sm120/attention/kda_linear.h"

#include "kda_reference.h"

#include "../gpu_test_utils.h"

#include <gtest/gtest.h>

#include <cuda_runtime.h>
#include <cuda_bf16.h>

#include <algorithm>
#include <cmath>
#include <cstdint>
#include <cstdio>
#include <cstring>
#include <filesystem>
#include <fstream>
#include <stdexcept>
#include <string>
#include <vector>

namespace lc = layerstorm::compute;
namespace sl = sm120::linear;

namespace {

using namespace layerstorm::kda_ref;

// ── geometry / hyper-parameters (must mirror the kernel contract) ───────────

constexpr int D = 128;              ///< head_dim, compile-fixed in the kernels
constexpr float kLowerBound = -5.0f;
constexpr float kL2Eps = 1e-6f;
constexpr float kONormEps = 1e-5f;

/// Host-computed scale — the kernels take it as a parameter precisely so the
/// constant is bit-identical to the CPU reference's KdaParams::scale().
float kda_scale() { return 1.0f / std::sqrt(static_cast<float>(D)); }

KdaParams ref_params(int num_heads) {
    KdaParams p;
    p.num_heads = num_heads;
    p.head_dim = D;
    p.lower_bound = kLowerBound;
    p.l2_eps = kL2Eps;
    p.onorm_eps = kONormEps;
    return p;
}

// ── device helpers (conventions from indexer_kpool_test.cu) ─────────────────

/// Owns every device allocation a test makes and cudaFrees them at scope exit.
class DevBag {
  public:
    DevBag() = default;
    DevBag(const DevBag&) = delete;
    DevBag& operator=(const DevBag&) = delete;
    ~DevBag() {
        for (void* p : ptrs_) cudaFree(p);
    }

    template <typename T>
    T* alloc(size_t n) {
        T* d = nullptr;
        EXPECT_EQ(cudaMalloc(&d, std::max<size_t>(n, 1) * sizeof(T)), cudaSuccess);
        ptrs_.push_back(static_cast<void*>(d));
        return d;
    }

    /// fp32 upload.
    float* f32(const std::vector<float>& h) {
        float* d = alloc<float>(h.size());
        EXPECT_EQ(cudaMemcpy(d, h.data(), h.size() * sizeof(float), cudaMemcpyHostToDevice),
                  cudaSuccess);
        return d;
    }
    /// zeroed fp32 buffer.
    float* f32z(size_t n) {
        float* d = alloc<float>(n);
        EXPECT_EQ(cudaMemset(d, 0, std::max<size_t>(n, 1) * sizeof(float)), cudaSuccess);
        return d;
    }
    /// fp32 host values -> bf16 device buffer. Fixture/synth inputs are already
    /// bf16-rounded (kda_ref::bf16_round), so this conversion is exact.
    __nv_bfloat16* bf16(const std::vector<float>& h) {
        std::vector<__nv_bfloat16> tmp(h.size());
        for (size_t i = 0; i < h.size(); ++i) tmp[i] = __float2bfloat16(h[i]);
        __nv_bfloat16* d = alloc<__nv_bfloat16>(tmp.size());
        EXPECT_EQ(cudaMemcpy(d, tmp.data(), tmp.size() * sizeof(__nv_bfloat16),
                             cudaMemcpyHostToDevice),
                  cudaSuccess);
        return d;
    }
    __nv_bfloat16* bf16z(size_t n) {
        __nv_bfloat16* d = alloc<__nv_bfloat16>(n);
        EXPECT_EQ(cudaMemset(d, 0, std::max<size_t>(n, 1) * sizeof(__nv_bfloat16)),
                  cudaSuccess);
        return d;
    }
    int* i32(const std::vector<int>& h) {
        int* d = alloc<int>(h.size());
        EXPECT_EQ(cudaMemcpy(d, h.data(), h.size() * sizeof(int), cudaMemcpyHostToDevice),
                  cudaSuccess);
        return d;
    }
    /// zeroed raw byte buffer (scan workspace).
    void* raw(size_t bytes) {
        void* d = nullptr;
        EXPECT_EQ(cudaMalloc(&d, std::max<size_t>(bytes, 1)), cudaSuccess);
        EXPECT_EQ(cudaMemset(d, 0, std::max<size_t>(bytes, 1)), cudaSuccess);
        ptrs_.push_back(d);
        return d;
    }

  private:
    std::vector<void*> ptrs_;
};

template <typename T>
std::vector<T> download(const void* d, size_t n) {
    std::vector<T> h(n);
    EXPECT_EQ(cudaMemcpy(h.data(), d, n * sizeof(T), cudaMemcpyDeviceToHost), cudaSuccess);
    return h;
}

std::vector<float> download_bf16_as_f32(const void* d, size_t n) {
    const std::vector<__nv_bfloat16> raw = download<__nv_bfloat16>(d, n);
    std::vector<float> h(n);
    for (size_t i = 0; i < n; ++i) h[i] = __bfloat162float(raw[i]);
    return h;
}

/// Conv ring layout bridge: the GPU ring is [3][C] (oldest tap first, one
/// coalesced row per tap), kda_ref::ConvState::ring is its transpose [C][3].
/// The VALUES are identical (the last 3 raw pre-conv inputs).
std::vector<float> ring_ref_to_gpu(const std::vector<float>& ref, int channels) {
    std::vector<float> g(static_cast<size_t>(channels) * 3, 0.0f);
    for (int ch = 0; ch < channels; ++ch) {
        for (int j = 0; j < 3; ++j) {
            g[static_cast<size_t>(j) * channels + ch] = ref[static_cast<size_t>(ch) * 3 + j];
        }
    }
    return g;
}

std::vector<float> ring_gpu_to_ref(const std::vector<float>& gpu, int channels) {
    std::vector<float> r(static_cast<size_t>(channels) * 3, 0.0f);
    for (int ch = 0; ch < channels; ++ch) {
        for (int j = 0; j < 3; ++j) {
            r[static_cast<size_t>(ch) * 3 + j] = gpu[static_cast<size_t>(j) * channels + ch];
        }
    }
    return r;
}

/// Byte-for-byte comparison of two float vectors (bitwise arms).
bool bit_equal(const std::vector<float>& a, const std::vector<float>& b) {
    if (a.size() != b.size()) return false;
    return std::memcmp(a.data(), b.data(), a.size() * sizeof(float)) == 0;
}

// ── comparison (copied from kda_reference_test.cpp, plus a [kda-tol] tap) ───

struct Closeness {
    double max_abs = 0, max_rel_excess = 0;
    size_t worst = 0;
};

// Scale-aware bound: |a_i - b_i| <= frac_scale * max|b| + frac_elem * |b_i|.
Closeness closeness(const std::vector<float>& a, const std::vector<float>& b,
                    double frac_scale, double frac_elem) {
    Closeness c;
    EXPECT_EQ(a.size(), b.size());
    double scale = 0;
    for (float x : b) scale = std::max(scale, std::abs(double(x)));
    if (scale == 0) scale = 1e-30;
    for (size_t i = 0; i < std::min(a.size(), b.size()); ++i) {
        const double d = std::abs(double(a[i]) - double(b[i]));
        const double bound = frac_scale * scale + frac_elem * std::abs(double(b[i]));
        if (d > c.max_abs) c.max_abs = d;
        const double excess = d / bound;
        if (excess > c.max_rel_excess) {
            c.max_rel_excess = excess;
            c.worst = i;
        }
    }
    return c;
}

/// Band check + UNCONDITIONAL measurement tap. The "[kda-tol]" lines are the
/// provenance for tightening the bands after a real GPU run (file header).
void expect_close(const std::vector<float>& a, const std::vector<float>& b, double frac_scale,
                  double frac_elem, const char* label) {
    const Closeness c = closeness(a, b, frac_scale, frac_elem);
    std::printf("[kda-tol] %-44s max_excess=%.4g max_abs=%.4g (bands %g/%g, n=%zu)\n", label,
                c.max_rel_excess, c.max_abs, frac_scale, frac_elem, b.size());
    std::fflush(stdout);
    EXPECT_LE(c.max_rel_excess, 1.0)
        << label << ": max_abs_diff=" << c.max_abs << " at flat index " << c.worst
        << " (gpu=" << (c.worst < a.size() ? a[c.worst] : 0.f)
        << " ref=" << (c.worst < b.size() ? b[c.worst] : 0.f)
        << ", frac_scale=" << frac_scale << ", frac_elem=" << frac_elem << ")";
}

void expect_close(const std::vector<float>& a, const std::vector<float>& b, double frac_scale,
                  double frac_elem, const std::string& label) {
    expect_close(a, b, frac_scale, frac_elem, label.c_str());
}

// ── fixture I/O (copied from kda_reference_test.cpp) ────────────────────────

std::string resolve_test_data(const std::string& rel) {
    namespace fs = std::filesystem;
    const std::vector<std::string> candidates = {
        rel,
        "../" + rel,
        "../../" + rel,
#ifdef LAYERSTORM_SOURCE_DIR
        std::string(LAYERSTORM_SOURCE_DIR) + "/" + rel,
#endif
    };
    for (const auto& c : candidates) {
        if (fs::exists(c)) return c;
    }
    return rel;  // let the open fail with the raw name in the message
}

std::vector<float> load_f32(const std::string& rel, size_t expect_count) {
    const std::string path = resolve_test_data(rel);
    std::ifstream f(path, std::ios::binary | std::ios::ate);
    EXPECT_TRUE(f.good()) << "missing fixture: " << path;
    if (!f.good()) return {};
    const size_t bytes = static_cast<size_t>(f.tellg());
    EXPECT_EQ(bytes, expect_count * 4) << path;
    std::vector<float> v(expect_count);
    f.seekg(0);
    f.read(reinterpret_cast<char*>(v.data()), static_cast<std::streamsize>(bytes));
    return v;
}

std::vector<float> load_bf16_as_f32(const std::string& rel, size_t expect_count) {
    const std::string path = resolve_test_data(rel);
    std::ifstream f(path, std::ios::binary | std::ios::ate);
    EXPECT_TRUE(f.good()) << "missing fixture: " << path;
    if (!f.good()) return {};
    const size_t bytes = static_cast<size_t>(f.tellg());
    EXPECT_EQ(bytes, expect_count * 2) << path;
    std::vector<uint16_t> raw(expect_count);
    f.seekg(0);
    f.read(reinterpret_cast<char*>(raw.data()), static_cast<std::streamsize>(bytes));
    std::vector<float> v(expect_count);
    for (size_t i = 0; i < expect_count; ++i) v[i] = bf16_to_f32(raw[i]);
    return v;
}

// ── deterministic inputs (same splitmix64 streams as the CPU reference and
//    tools/gen_kda_golden.py — the goldens are only meaningful if these agree) ─

std::vector<float> synth(uint64_t seed, size_t n, float lo, float hi, bool round_bf16) {
    std::vector<float> v(n);
    uint64_t s = seed;
    for (auto& x : v) {
        x = splitmix_uniform(s, lo, hi);
        if (round_bf16) x = bf16_round(x);
    }
    return v;
}

/// Full end-to-end input bundle (raw pre-conv activations + all parameters),
/// identical to kda_reference_test.cpp's ScanInputs.
struct ScanInputs {
    std::vector<float> q, k, v, raw_g, g2, beta, a_log, dt_bias;
    std::vector<float> conv_wq, conv_wk, conv_wv, onorm_w, s0, cs_q, cs_k, cs_v;
};

ScanInputs make_inputs(const KdaParams& p, int t_len, uint64_t seed_base) {
    ScanInputs in;
    const size_t n = static_cast<size_t>(t_len) * p.channels();
    const size_t c = p.channels();
    in.q = synth(seed_base + 0, n, -1.0f, 1.0f, true);
    in.k = synth(seed_base + 1, n, -1.0f, 1.0f, true);
    in.v = synth(seed_base + 2, n, -1.0f, 1.0f, true);
    in.raw_g = synth(seed_base + 3, n, -3.0f, 3.0f, true);
    in.g2 = synth(seed_base + 4, n, -2.0f, 2.0f, true);
    in.beta = synth(seed_base + 5, static_cast<size_t>(t_len) * p.num_heads, -2.0f, 2.0f, true);
    in.a_log = synth(seed_base + 6, p.num_heads, -1.0f, 1.5f, false);
    in.dt_bias = synth(seed_base + 7, c, -1.0f, 1.0f, false);
    in.conv_wq = synth(seed_base + 8, c * p.conv_width, -0.5f, 0.5f, true);
    in.conv_wk = synth(seed_base + 9, c * p.conv_width, -0.5f, 0.5f, true);
    in.conv_wv = synth(seed_base + 10, c * p.conv_width, -0.5f, 0.5f, true);
    in.onorm_w = synth(seed_base + 11, p.head_dim, 0.5f, 1.5f, true);
    in.s0 = synth(seed_base + 12, static_cast<size_t>(p.num_heads) * p.head_dim * p.head_dim,
                  -1.0f, 1.0f, false);
    in.cs_q = synth(seed_base + 13, c * (p.conv_width - 1), -1.0f, 1.0f, true);
    in.cs_k = synth(seed_base + 14, c * (p.conv_width - 1), -1.0f, 1.0f, true);
    in.cs_v = synth(seed_base + 15, c * (p.conv_width - 1), -1.0f, 1.0f, true);
    return in;
}

struct ScanResult {
    std::vector<float> core, onorm;
    KdaState st;
    ConvState cq, ck, cv;
};

/// CPU end-to-end scan (conv -> scan -> o_norm) on the reference.
ScanResult run_ref_scan(const KdaParams& p, ScanPath path, const ScanInputs& in, int t_len) {
    ScanResult r;
    const size_t n = static_cast<size_t>(t_len) * p.channels();
    r.core.assign(n, 0.0f);
    r.onorm.assign(n, 0.0f);
    r.st = KdaState::zeros(p);
    if (!in.s0.empty()) r.st.s = in.s0;
    r.cq = ConvState::zeros(p);
    r.ck = ConvState::zeros(p);
    r.cv = ConvState::zeros(p);
    if (!in.cs_q.empty()) r.cq.ring = in.cs_q;
    if (!in.cs_k.empty()) r.ck.ring = in.cs_k;
    if (!in.cs_v.empty()) r.cv.ring = in.cs_v;
    kda_scan(p, path, in.q.data(), in.k.data(), in.v.data(), in.raw_g.data(), in.g2.data(),
             in.beta.data(), in.a_log.data(), in.dt_bias.data(), in.conv_wq.data(),
             in.conv_wk.data(), in.conv_wv.data(), in.onorm_w.data(), t_len, r.st, r.cq, r.ck,
             r.cv, r.core.data(), r.onorm.data());
    return r;
}

/// POST-conv input bundle for the scan/decode kernels: q/k/v are already what
/// the conv would have produced (bf16-valued fp32 — benign magnitudes, and
/// exactly representable so the CPU and GPU see the same numbers).
struct ScanKernelInputs {
    std::vector<float> q, k, v;   // post-conv fp32, [T][H*128]
    std::vector<float> raw_g;     // [T][H*128] bf16-valued
    std::vector<float> beta;      // [T][H] bf16-valued (pre-sigmoid)
    std::vector<float> g2;        // [T][H*128] bf16-valued
    std::vector<float> a_log;     // [H] fp32, NOT rounded
    std::vector<float> dt_bias;   // [H*128] fp32, NOT rounded
    std::vector<float> onorm_w;   // [128] bf16-valued
    std::vector<float> s0;        // [H][128][128] fp32, NOT rounded
};

ScanKernelInputs make_scan_kernel_inputs(int heads, int t_len, uint64_t seed) {
    const size_t c = static_cast<size_t>(heads) * D;
    const size_t n = static_cast<size_t>(t_len) * c;
    ScanKernelInputs in;
    in.q = synth(seed + 0, n, -1.0f, 1.0f, true);
    in.k = synth(seed + 1, n, -1.0f, 1.0f, true);
    in.v = synth(seed + 2, n, -1.0f, 1.0f, true);
    in.raw_g = synth(seed + 3, n, -3.0f, 3.0f, true);
    in.beta = synth(seed + 4, static_cast<size_t>(t_len) * heads, -2.0f, 2.0f, true);
    in.g2 = synth(seed + 5, n, -2.0f, 2.0f, true);
    in.a_log = synth(seed + 6, heads, -1.0f, 1.5f, false);
    in.dt_bias = synth(seed + 7, c, -1.0f, 1.0f, false);
    in.onorm_w = synth(seed + 8, D, 0.5f, 1.5f, true);
    in.s0 = synth(seed + 9, static_cast<size_t>(heads) * D * D, -1.0f, 1.0f, false);
    return in;
}

// ═══════════════════════════════════════════════════════════════════════════
// (iii) Short conv — launch_kda_conv_prefill / launch_kda_conv_decode
// ═══════════════════════════════════════════════════════════════════════════

// Post-SiLU outputs vs kda_ref::conv_prefill on the same fp32 inputs, and the
// carried rings BITWISE (they hold raw bf16-valued inputs, so any deviation is
// a layout/indexing bug, not arithmetic). Bands are tight on purpose: the only
// legitimate divergence is fast-math sigmoid inside SiLU.
TEST(KdaConvKernel, PrefillMatchesReference) {
    REQUIRES_GPU();
    const int H = 4, T = 150;
    const KdaParams p = ref_params(H);
    const int C = p.channels();  // 512
    const size_t n = static_cast<size_t>(T) * C;
    const size_t rn = static_cast<size_t>(C) * 3;

    const auto xq = synth(41001, n, -1.0f, 1.0f, true);
    const auto xk = synth(41002, n, -1.0f, 1.0f, true);
    const auto xv = synth(41003, n, -1.0f, 1.0f, true);
    const auto wq = synth(41004, static_cast<size_t>(C) * 4, -0.5f, 0.5f, true);
    const auto wk = synth(41005, static_cast<size_t>(C) * 4, -0.5f, 0.5f, true);
    const auto wv = synth(41006, static_cast<size_t>(C) * 4, -0.5f, 0.5f, true);
    const auto r0q = synth(41007, rn, -1.0f, 1.0f, true);  // [C][3] reference layout
    const auto r0k = synth(41008, rn, -1.0f, 1.0f, true);
    const auto r0v = synth(41009, rn, -1.0f, 1.0f, true);

    // CPU reference (nonzero initial rings).
    ConvState cq = ConvState::zeros(p), ck = ConvState::zeros(p), cv = ConvState::zeros(p);
    cq.ring = r0q;
    ck.ring = r0k;
    cv.ring = r0v;
    std::vector<float> refq(n), refk(n), refv(n);
    conv_prefill(p, xq.data(), T, wq.data(), cq, refq.data());
    conv_prefill(p, xk.data(), T, wk.data(), ck, refk.data());
    conv_prefill(p, xv.data(), T, wv.data(), cv, refv.data());

    DevBag bag;
    sl::KdaConvPrefillParams cp{};
    cp.x_q = bag.bf16(xq);
    cp.x_k = bag.bf16(xk);
    cp.x_v = bag.bf16(xv);
    cp.w_q = bag.bf16(wq);
    cp.w_k = bag.bf16(wk);
    cp.w_v = bag.bf16(wv);
    float* rq = bag.f32(ring_ref_to_gpu(r0q, C));
    float* rk = bag.f32(ring_ref_to_gpu(r0k, C));
    float* rv = bag.f32(ring_ref_to_gpu(r0v, C));
    cp.ring_q = rq;
    cp.ring_k = rk;
    cp.ring_v = rv;
    float* oq = bag.f32z(n);
    float* ok = bag.f32z(n);
    float* ov = bag.f32z(n);
    cp.out_q = oq;
    cp.out_k = ok;
    cp.out_v = ov;
    cp.t_len = T;
    cp.channels = C;
    lc::launch_kda_conv_prefill(cp, nullptr);
    ASSERT_EQ(cudaDeviceSynchronize(), cudaSuccess);

    expect_close(download<float>(oq, n), refq, 1e-6, 1e-5, "conv prefill out_q");
    expect_close(download<float>(ok, n), refk, 1e-6, 1e-5, "conv prefill out_k");
    expect_close(download<float>(ov, n), refv, 1e-6, 1e-5, "conv prefill out_v");

    // Rings: exact (raw inputs round-tripped through fp32), after transposing
    // the GPU's [3][C] back to the reference's [C][3].
    const auto gq = ring_gpu_to_ref(download<float>(rq, rn), C);
    const auto gk = ring_gpu_to_ref(download<float>(rk, rn), C);
    const auto gv = ring_gpu_to_ref(download<float>(rv, rn), C);
    for (size_t i = 0; i < rn; ++i) {
        ASSERT_EQ(gq[i], cq.ring[i]) << "ring_q @" << i;
        ASSERT_EQ(gk[i], ck.ring[i]) << "ring_k @" << i;
        ASSERT_EQ(gv[i], cv.ring[i]) << "ring_v @" << i;
    }
}

// The conv is a pure per-channel ring: splitting a prefill anywhere and
// carrying (ring_q/k/v) through global memory is BITWISE identical to the
// one-shot launch. GPU vs GPU — no reference involved.
TEST(KdaConvKernel, SplitIsBitwise) {
    REQUIRES_GPU();
    const int H = 4, T = 150, split = 97;
    const KdaParams p = ref_params(H);
    const int C = p.channels();
    const size_t n = static_cast<size_t>(T) * C;
    const size_t rn = static_cast<size_t>(C) * 3;

    DevBag bag;
    const __nv_bfloat16* xq = bag.bf16(synth(42001, n, -1.0f, 1.0f, true));
    const __nv_bfloat16* xk = bag.bf16(synth(42002, n, -1.0f, 1.0f, true));
    const __nv_bfloat16* xv = bag.bf16(synth(42003, n, -1.0f, 1.0f, true));
    const __nv_bfloat16* wq = bag.bf16(synth(42004, static_cast<size_t>(C) * 4, -0.5f, 0.5f, true));
    const __nv_bfloat16* wk = bag.bf16(synth(42005, static_cast<size_t>(C) * 4, -0.5f, 0.5f, true));
    const __nv_bfloat16* wv = bag.bf16(synth(42006, static_cast<size_t>(C) * 4, -0.5f, 0.5f, true));
    const auto r0q = ring_ref_to_gpu(synth(42007, rn, -1.0f, 1.0f, true), C);
    const auto r0k = ring_ref_to_gpu(synth(42008, rn, -1.0f, 1.0f, true), C);
    const auto r0v = ring_ref_to_gpu(synth(42009, rn, -1.0f, 1.0f, true), C);

    float* ra[3] = {bag.f32(r0q), bag.f32(r0k), bag.f32(r0v)};
    float* rb[3] = {bag.f32(r0q), bag.f32(r0k), bag.f32(r0v)};
    float* oa[3] = {bag.f32z(n), bag.f32z(n), bag.f32z(n)};
    float* ob[3] = {bag.f32z(n), bag.f32z(n), bag.f32z(n)};

    auto run = [&](float* const* rings, float* const* outs, int t0, int len) {
        sl::KdaConvPrefillParams cp{};
        cp.x_q = xq + static_cast<size_t>(t0) * C;
        cp.x_k = xk + static_cast<size_t>(t0) * C;
        cp.x_v = xv + static_cast<size_t>(t0) * C;
        cp.w_q = wq;
        cp.w_k = wk;
        cp.w_v = wv;
        cp.ring_q = rings[0];
        cp.ring_k = rings[1];
        cp.ring_v = rings[2];
        cp.out_q = outs[0] + static_cast<size_t>(t0) * C;
        cp.out_k = outs[1] + static_cast<size_t>(t0) * C;
        cp.out_v = outs[2] + static_cast<size_t>(t0) * C;
        cp.t_len = len;
        cp.channels = C;
        lc::launch_kda_conv_prefill(cp, nullptr);
    };

    run(ra, oa, 0, T);
    run(rb, ob, 0, split);
    run(rb, ob, split, T - split);
    ASSERT_EQ(cudaDeviceSynchronize(), cudaSuccess);

    const char* tag[3] = {"q", "k", "v"};
    for (int i = 0; i < 3; ++i) {
        EXPECT_TRUE(bit_equal(download<float>(oa[i], n), download<float>(ob[i], n)))
            << "conv split out_" << tag[i] << " is not bitwise (split @" << split << ")";
        EXPECT_TRUE(bit_equal(download<float>(ra[i], rn), download<float>(rb[i], rn)))
            << "conv split ring_" << tag[i] << " is not bitwise (split @" << split << ")";
    }
}

// The decode kernel is the same arithmetic as one prefill column: five
// sequential single-token decode launches must reproduce a five-token prefill
// BIT-FOR-BIT (outputs and rings). If fast-math scheduling ever makes this
// flaky it is a real finding about the two kernels' SiLU/FMA forms — the
// assert stays EQ deliberately.
TEST(KdaConvKernel, DecodeStepMatchesPrefillColumn) {
    REQUIRES_GPU();
    const int H = 4, T = 5;
    const KdaParams p = ref_params(H);
    const int C = p.channels();
    const size_t n = static_cast<size_t>(T) * C;
    const size_t rn = static_cast<size_t>(C) * 3;

    DevBag bag;
    const __nv_bfloat16* xq = bag.bf16(synth(43001, n, -1.0f, 1.0f, true));
    const __nv_bfloat16* xk = bag.bf16(synth(43002, n, -1.0f, 1.0f, true));
    const __nv_bfloat16* xv = bag.bf16(synth(43003, n, -1.0f, 1.0f, true));
    const __nv_bfloat16* wq = bag.bf16(synth(43004, static_cast<size_t>(C) * 4, -0.5f, 0.5f, true));
    const __nv_bfloat16* wk = bag.bf16(synth(43005, static_cast<size_t>(C) * 4, -0.5f, 0.5f, true));
    const __nv_bfloat16* wv = bag.bf16(synth(43006, static_cast<size_t>(C) * 4, -0.5f, 0.5f, true));
    const auto r0q = ring_ref_to_gpu(synth(43007, rn, -1.0f, 1.0f, true), C);
    const auto r0k = ring_ref_to_gpu(synth(43008, rn, -1.0f, 1.0f, true), C);
    const auto r0v = ring_ref_to_gpu(synth(43009, rn, -1.0f, 1.0f, true), C);

    float* rp[3] = {bag.f32(r0q), bag.f32(r0k), bag.f32(r0v)};  // prefill arm
    float* rd[3] = {bag.f32(r0q), bag.f32(r0k), bag.f32(r0v)};  // decode arm
    float* op[3] = {bag.f32z(n), bag.f32z(n), bag.f32z(n)};
    float* od[3] = {bag.f32z(n), bag.f32z(n), bag.f32z(n)};

    {
        sl::KdaConvPrefillParams cp{};
        cp.x_q = xq; cp.x_k = xk; cp.x_v = xv;
        cp.w_q = wq; cp.w_k = wk; cp.w_v = wv;
        cp.ring_q = rp[0]; cp.ring_k = rp[1]; cp.ring_v = rp[2];
        cp.out_q = op[0]; cp.out_k = op[1]; cp.out_v = op[2];
        cp.t_len = T;
        cp.channels = C;
        lc::launch_kda_conv_prefill(cp, nullptr);
    }
    for (int t = 0; t < T; ++t) {
        sl::KdaConvDecodeParams dp{};
        dp.x_q = xq + static_cast<size_t>(t) * C;
        dp.x_k = xk + static_cast<size_t>(t) * C;
        dp.x_v = xv + static_cast<size_t>(t) * C;
        dp.w_q = wq; dp.w_k = wk; dp.w_v = wv;
        dp.ring_q = rd[0]; dp.ring_k = rd[1]; dp.ring_v = rd[2];
        dp.slots = nullptr;
        dp.ring_slot_stride = static_cast<int64_t>(3) * C;
        dp.out_q = od[0] + static_cast<size_t>(t) * C;
        dp.out_k = od[1] + static_cast<size_t>(t) * C;
        dp.out_v = od[2] + static_cast<size_t>(t) * C;
        dp.batch = 1;
        dp.channels = C;
        lc::launch_kda_conv_decode(dp, nullptr);
    }
    ASSERT_EQ(cudaDeviceSynchronize(), cudaSuccess);

    const char* tag[3] = {"q", "k", "v"};
    for (int i = 0; i < 3; ++i) {
        const auto a = download<float>(op[i], n);
        const auto b = download<float>(od[i], n);
        for (size_t j = 0; j < n; ++j) {
            ASSERT_EQ(a[j], b[j]) << "conv decode vs prefill out_" << tag[i] << " @" << j;
        }
        EXPECT_TRUE(bit_equal(download<float>(rp[i], rn), download<float>(rd[i], rn)))
            << "conv decode vs prefill ring_" << tag[i];
    }
}

// Slot indirection: a batch of 3 sequences writing into a 3-slot ring buffer
// through slots = {2,0,1} must match three independent single-sequence runs
// bitwise (same kernel, same arithmetic — only the addressing differs).
TEST(KdaConvKernel, DecodeBatchSlots) {
    REQUIRES_GPU();
    const int H = 4, B = 3;
    const KdaParams p = ref_params(H);
    const int C = p.channels();
    const size_t rn = static_cast<size_t>(C) * 3;
    const std::vector<int> slots = {2, 0, 1};

    DevBag bag;
    // One row of raw input per sequence, packed [B][C].
    const auto hxq = synth(44001, static_cast<size_t>(B) * C, -1.0f, 1.0f, true);
    const auto hxk = synth(44002, static_cast<size_t>(B) * C, -1.0f, 1.0f, true);
    const auto hxv = synth(44003, static_cast<size_t>(B) * C, -1.0f, 1.0f, true);
    const __nv_bfloat16* xq = bag.bf16(hxq);
    const __nv_bfloat16* xk = bag.bf16(hxk);
    const __nv_bfloat16* xv = bag.bf16(hxv);
    const __nv_bfloat16* wq = bag.bf16(synth(44004, static_cast<size_t>(C) * 4, -0.5f, 0.5f, true));
    const __nv_bfloat16* wk = bag.bf16(synth(44005, static_cast<size_t>(C) * 4, -0.5f, 0.5f, true));
    const __nv_bfloat16* wv = bag.bf16(synth(44006, static_cast<size_t>(C) * 4, -0.5f, 0.5f, true));

    // Distinct initial rings per sequence (GPU [3][C] layout).
    std::vector<std::vector<float>> r0q(B), r0k(B), r0v(B);
    for (int b = 0; b < B; ++b) {
        r0q[b] = ring_ref_to_gpu(synth(44010 + b, rn, -1.0f, 1.0f, true), C);
        r0k[b] = ring_ref_to_gpu(synth(44020 + b, rn, -1.0f, 1.0f, true), C);
        r0v[b] = ring_ref_to_gpu(synth(44030 + b, rn, -1.0f, 1.0f, true), C);
    }

    // Batched arm: [3 slots][3][C] ring buffers, sequence b living in slots[b].
    std::vector<float> packq(rn * B, 0.0f), packk(rn * B, 0.0f), packv(rn * B, 0.0f);
    for (int b = 0; b < B; ++b) {
        const size_t off = static_cast<size_t>(slots[b]) * rn;
        std::copy(r0q[b].begin(), r0q[b].end(), packq.begin() + off);
        std::copy(r0k[b].begin(), r0k[b].end(), packk.begin() + off);
        std::copy(r0v[b].begin(), r0v[b].end(), packv.begin() + off);
    }
    float* brq = bag.f32(packq);
    float* brk = bag.f32(packk);
    float* brv = bag.f32(packv);
    float* boq = bag.f32z(static_cast<size_t>(B) * C);
    float* bok = bag.f32z(static_cast<size_t>(B) * C);
    float* bov = bag.f32z(static_cast<size_t>(B) * C);
    {
        sl::KdaConvDecodeParams dp{};
        dp.x_q = xq; dp.x_k = xk; dp.x_v = xv;
        dp.w_q = wq; dp.w_k = wk; dp.w_v = wv;
        dp.ring_q = brq; dp.ring_k = brk; dp.ring_v = brv;
        dp.slots = bag.i32(slots);
        dp.ring_slot_stride = static_cast<int64_t>(rn);
        dp.out_q = boq; dp.out_k = bok; dp.out_v = bov;
        dp.batch = B;
        dp.channels = C;
        lc::launch_kda_conv_decode(dp, nullptr);
    }

    // Reference arm: one launch per sequence into its own single-slot buffer.
    std::vector<float*> srq(B), srk(B), srv(B), soq(B), sok(B), sov(B);
    for (int b = 0; b < B; ++b) {
        srq[b] = bag.f32(r0q[b]);
        srk[b] = bag.f32(r0k[b]);
        srv[b] = bag.f32(r0v[b]);
        soq[b] = bag.f32z(C);
        sok[b] = bag.f32z(C);
        sov[b] = bag.f32z(C);
        sl::KdaConvDecodeParams dp{};
        dp.x_q = xq + static_cast<size_t>(b) * C;
        dp.x_k = xk + static_cast<size_t>(b) * C;
        dp.x_v = xv + static_cast<size_t>(b) * C;
        dp.w_q = wq; dp.w_k = wk; dp.w_v = wv;
        dp.ring_q = srq[b]; dp.ring_k = srk[b]; dp.ring_v = srv[b];
        dp.slots = nullptr;
        dp.ring_slot_stride = static_cast<int64_t>(rn);
        dp.out_q = soq[b]; dp.out_k = sok[b]; dp.out_v = sov[b];
        dp.batch = 1;
        dp.channels = C;
        lc::launch_kda_conv_decode(dp, nullptr);
    }
    ASSERT_EQ(cudaDeviceSynchronize(), cudaSuccess);

    const auto gq = download<float>(brq, rn * B);
    const auto gk = download<float>(brk, rn * B);
    const auto gv = download<float>(brv, rn * B);
    const auto oq = download<float>(boq, static_cast<size_t>(B) * C);
    const auto ok = download<float>(bok, static_cast<size_t>(B) * C);
    const auto ov = download<float>(bov, static_cast<size_t>(B) * C);
    for (int b = 0; b < B; ++b) {
        const size_t roff = static_cast<size_t>(slots[b]) * rn;
        const size_t coff = static_cast<size_t>(b) * C;
        const auto rq1 = download<float>(srq[b], rn);
        const auto rk1 = download<float>(srk[b], rn);
        const auto rv1 = download<float>(srv[b], rn);
        const auto oq1 = download<float>(soq[b], C);
        const auto ok1 = download<float>(sok[b], C);
        const auto ov1 = download<float>(sov[b], C);
        for (size_t i = 0; i < rn; ++i) {
            ASSERT_EQ(gq[roff + i], rq1[i]) << "batch ring_q b=" << b << " @" << i;
            ASSERT_EQ(gk[roff + i], rk1[i]) << "batch ring_k b=" << b << " @" << i;
            ASSERT_EQ(gv[roff + i], rv1[i]) << "batch ring_v b=" << b << " @" << i;
        }
        for (int c = 0; c < C; ++c) {
            ASSERT_EQ(oq[coff + c], oq1[c]) << "batch out_q b=" << b << " @" << c;
            ASSERT_EQ(ok[coff + c], ok1[c]) << "batch out_k b=" << b << " @" << c;
            ASSERT_EQ(ov[coff + c], ov1[c]) << "batch out_v b=" << b << " @" << c;
        }
    }
}

// ═══════════════════════════════════════════════════════════════════════════
// (ii) Fused O(1) decode step — launch_kda_decode_step
// ═══════════════════════════════════════════════════════════════════════════

/// One token, one sequence, nonzero initial state: core (pre-o_norm), the
/// o_norm f32 tap and the mutated state, all against
/// kda_ref::recurrent_step + kda_ref::gated_rmsnorm.
void decode_step_case(int heads, uint64_t seed, const char* tag) {
    const KdaParams p = ref_params(heads);
    const int C = p.channels();
    const size_t sn = static_cast<size_t>(heads) * D * D;
    const ScanKernelInputs in = make_scan_kernel_inputs(heads, 1, seed);

    // CPU reference (q/k/v are POST-conv activations — recurrent_step's input).
    KdaState st = KdaState::zeros(p);
    st.s = in.s0;
    std::vector<float> ref_core(C), ref_onorm(C);
    recurrent_step(p, in.q.data(), in.k.data(), in.v.data(), in.raw_g.data(), in.beta.data(),
                   in.a_log.data(), in.dt_bias.data(), st, ref_core.data());
    gated_rmsnorm(p, ref_core.data(), in.g2.data(), in.onorm_w.data(), 1, ref_onorm.data());

    DevBag bag;
    float* state = bag.f32(in.s0);
    float* core = bag.f32z(C);
    float* onorm = bag.f32z(C);
    sl::KdaDecodeStepParams dp{};
    dp.q = bag.f32(in.q);
    dp.k = bag.f32(in.k);
    dp.v = bag.f32(in.v);
    dp.raw_g = bag.bf16(in.raw_g);
    dp.beta = bag.bf16(in.beta);
    dp.g2 = bag.bf16(in.g2);
    dp.a_log = bag.f32(in.a_log);
    dp.dt_bias = bag.f32(in.dt_bias);
    dp.onorm_w = bag.bf16(in.onorm_w);
    dp.state_base = state;
    dp.state_slot_stride = static_cast<int64_t>(sn);
    dp.slots = nullptr;
    dp.core_out = core;
    dp.out_bf16 = nullptr;
    dp.out_f32 = onorm;
    dp.batch = 1;
    dp.num_heads = heads;
    dp.lower_bound = kLowerBound;
    dp.l2_eps = kL2Eps;
    dp.onorm_eps = kONormEps;
    dp.scale = kda_scale();
    lc::launch_kda_decode_step(dp, nullptr);
    ASSERT_EQ(cudaDeviceSynchronize(), cudaSuccess);

    const std::string t(tag);
    expect_close(download<float>(core, C), ref_core, 2e-5, 2e-4, t + " decode core");
    expect_close(download<float>(onorm, C), ref_onorm, 2e-5, 2e-4, t + " decode onorm");
    expect_close(download<float>(state, sn), st.s, 2e-5, 2e-4, t + " decode state");
}

TEST(KdaDecodeKernel, StepMatchesReference) {
    REQUIRES_GPU();
    decode_step_case(4, 45000, "H=4");
}

// Shipped GLM-5.3-Flash head count: 64 heads => 4 MiB of fp32 state touched
// exactly once by the fused kernel. Same bands — head count must not move the
// numerics (heads are independent).
TEST(KdaDecodeKernel, HeadCount64) {
    REQUIRES_GPU();
    decode_step_case(64, 46000, "H=64");
}

// State-slot indirection (GF3.8's paged state pool plugs in here): three
// sequences with DISTINCT states writing through slots = {1,2,0} must equal
// three independent single-sequence runs BITWISE.
TEST(KdaDecodeKernel, SlotIndirection) {
    REQUIRES_GPU();
    const int H = 2, B = 3;
    const KdaParams p = ref_params(H);
    const int C = p.channels();
    const size_t sn = static_cast<size_t>(H) * D * D;
    const std::vector<int> slots = {1, 2, 0};

    DevBag bag;
    const ScanKernelInputs in = make_scan_kernel_inputs(H, B, 47000);  // B "tokens" = B seqs
    // Distinct initial states, one per sequence.
    std::vector<std::vector<float>> s0(B);
    for (int b = 0; b < B; ++b) s0[b] = synth(47100 + b, sn, -1.0f, 1.0f, false);

    std::vector<float> packed(sn * B, 0.0f);
    for (int b = 0; b < B; ++b) {
        std::copy(s0[b].begin(), s0[b].end(),
                  packed.begin() + static_cast<size_t>(slots[b]) * sn);
    }

    const float* q = bag.f32(in.q);
    const float* k = bag.f32(in.k);
    const float* v = bag.f32(in.v);
    const __nv_bfloat16* rg = bag.bf16(in.raw_g);
    const __nv_bfloat16* bt = bag.bf16(in.beta);
    const __nv_bfloat16* g2 = bag.bf16(in.g2);
    const float* alog = bag.f32(in.a_log);
    const float* dtb = bag.f32(in.dt_bias);
    const __nv_bfloat16* ow = bag.bf16(in.onorm_w);

    auto fill = [&](sl::KdaDecodeStepParams& dp) {
        dp.a_log = alog;
        dp.dt_bias = dtb;
        dp.onorm_w = ow;
        dp.state_slot_stride = static_cast<int64_t>(sn);
        dp.out_bf16 = nullptr;
        dp.num_heads = H;
        dp.lower_bound = kLowerBound;
        dp.l2_eps = kL2Eps;
        dp.onorm_eps = kONormEps;
        dp.scale = kda_scale();
    };

    float* bstate = bag.f32(packed);
    float* bcore = bag.f32z(static_cast<size_t>(B) * C);
    float* bonorm = bag.f32z(static_cast<size_t>(B) * C);
    {
        sl::KdaDecodeStepParams dp{};
        fill(dp);
        dp.q = q; dp.k = k; dp.v = v;
        dp.raw_g = rg; dp.beta = bt; dp.g2 = g2;
        dp.state_base = bstate;
        dp.slots = bag.i32(slots);
        dp.core_out = bcore;
        dp.out_f32 = bonorm;
        dp.batch = B;
        lc::launch_kda_decode_step(dp, nullptr);
    }

    std::vector<float*> sstate(B), score(B), sonorm(B);
    for (int b = 0; b < B; ++b) {
        sstate[b] = bag.f32(s0[b]);
        score[b] = bag.f32z(C);
        sonorm[b] = bag.f32z(C);
        sl::KdaDecodeStepParams dp{};
        fill(dp);
        dp.q = q + static_cast<size_t>(b) * C;
        dp.k = k + static_cast<size_t>(b) * C;
        dp.v = v + static_cast<size_t>(b) * C;
        dp.raw_g = rg + static_cast<size_t>(b) * C;
        dp.beta = bt + static_cast<size_t>(b) * H;
        dp.g2 = g2 + static_cast<size_t>(b) * C;
        dp.state_base = sstate[b];
        dp.slots = nullptr;
        dp.core_out = score[b];
        dp.out_f32 = sonorm[b];
        dp.batch = 1;
        lc::launch_kda_decode_step(dp, nullptr);
    }
    ASSERT_EQ(cudaDeviceSynchronize(), cudaSuccess);

    const auto gstate = download<float>(bstate, sn * B);
    const auto gcore = download<float>(bcore, static_cast<size_t>(B) * C);
    const auto gonorm = download<float>(bonorm, static_cast<size_t>(B) * C);
    for (int b = 0; b < B; ++b) {
        const auto s1 = download<float>(sstate[b], sn);
        const auto c1 = download<float>(score[b], C);
        const auto o1 = download<float>(sonorm[b], C);
        const size_t soff = static_cast<size_t>(slots[b]) * sn;
        const size_t coff = static_cast<size_t>(b) * C;
        EXPECT_EQ(std::memcmp(gstate.data() + soff, s1.data(), sn * sizeof(float)), 0)
            << "slot-indirected state differs from the single-sequence run, b=" << b;
        EXPECT_EQ(std::memcmp(gcore.data() + coff, c1.data(), C * sizeof(float)), 0)
            << "slot-indirected core differs, b=" << b;
        EXPECT_EQ(std::memcmp(gonorm.data() + coff, o1.data(), C * sizeof(float)), 0)
            << "slot-indirected onorm differs, b=" << b;
    }
}

// TD-KDA-DECODE-PIPELINE: the 3-stage cp.async state staging changes WHEN
// state bytes move, never WHAT is computed — each lane stages exactly the 16
// bytes it consumes, the FMA/reduction order is untouched, so plain and
// pipelined variants must be BIT-IDENTICAL in state, core, o_norm f32 AND
// bf16 output. Locked at the golden geometry (H=4), the shipped head count
// (H=64) and under batched slot indirection.
void pipeline_bit_identity_case(int heads, int batch, uint64_t seed) {
    const int C = heads * D;
    const size_t sn = static_cast<size_t>(heads) * D * D;
    const ScanKernelInputs in = make_scan_kernel_inputs(heads, batch, seed);
    std::vector<float> packed(sn * static_cast<size_t>(batch));
    for (int b = 0; b < batch; ++b) {
        const auto st = synth(seed + 100 + static_cast<uint64_t>(b), sn,
                              -1.0f, 1.0f, false);
        std::copy(st.begin(), st.end(),
                  packed.begin() + static_cast<size_t>(b) * sn);
    }
    // Reverse slot order so the indirection is exercised too.
    std::vector<int> slots(static_cast<size_t>(batch));
    for (int b = 0; b < batch; ++b) slots[static_cast<size_t>(b)] = batch - 1 - b;
    std::vector<float> arm_state[2];
    std::vector<float> arm_core[2], arm_onorm[2];
    std::vector<__nv_bfloat16> arm_bf16[2];
    for (int arm = 0; arm < 2; ++arm) {
        DevBag bag;
        float* state = bag.f32(packed);
        float* core = bag.f32z(static_cast<size_t>(batch) * C);
        float* onorm = bag.f32z(static_cast<size_t>(batch) * C);
        __nv_bfloat16* obf = bag.bf16z(static_cast<size_t>(batch) * C);
        sl::KdaDecodeStepParams dp{};
        dp.q = bag.f32(in.q);
        dp.k = bag.f32(in.k);
        dp.v = bag.f32(in.v);
        dp.raw_g = bag.bf16(in.raw_g);
        dp.beta = bag.bf16(in.beta);
        dp.g2 = bag.bf16(in.g2);
        dp.a_log = bag.f32(in.a_log);
        dp.dt_bias = bag.f32(in.dt_bias);
        dp.onorm_w = bag.bf16(in.onorm_w);
        dp.state_base = state;
        dp.state_slot_stride = static_cast<int64_t>(sn);
        dp.slots = bag.i32(slots);
        dp.core_out = core;
        dp.out_bf16 = obf;
        dp.out_f32 = onorm;
        dp.batch = batch;
        dp.num_heads = heads;
        dp.lower_bound = kLowerBound;
        dp.l2_eps = kL2Eps;
        dp.onorm_eps = kONormEps;
        dp.scale = kda_scale();
        sl::run_kda_decode_step_variant(dp, nullptr, /*pipeline=*/arm == 1);
        ASSERT_EQ(cudaDeviceSynchronize(), cudaSuccess);
        arm_state[arm] = download<float>(state, packed.size());
        arm_core[arm] = download<float>(core, static_cast<size_t>(batch) * C);
        arm_onorm[arm] =
            download<float>(onorm, static_cast<size_t>(batch) * C);
        arm_bf16[arm] =
            download<__nv_bfloat16>(obf, static_cast<size_t>(batch) * C);
    }
    EXPECT_EQ(std::memcmp(arm_state[0].data(), arm_state[1].data(),
                          arm_state[0].size() * sizeof(float)), 0)
        << "pipeline changed STATE bytes (H=" << heads << " B=" << batch << ")";
    EXPECT_EQ(std::memcmp(arm_core[0].data(), arm_core[1].data(),
                          arm_core[0].size() * sizeof(float)), 0)
        << "pipeline changed core bytes";
    EXPECT_EQ(std::memcmp(arm_onorm[0].data(), arm_onorm[1].data(),
                          arm_onorm[0].size() * sizeof(float)), 0)
        << "pipeline changed o_norm f32 bytes";
    EXPECT_EQ(std::memcmp(arm_bf16[0].data(), arm_bf16[1].data(),
                          arm_bf16[0].size() * sizeof(__nv_bfloat16)), 0)
        << "pipeline changed bf16 output bytes";
}

TEST(KdaDecodeKernel, PipelineBitIdentity) {
    REQUIRES_GPU();
    pipeline_bit_identity_case(4, 1, 49000);
    pipeline_bit_identity_case(64, 1, 49100);
    pipeline_bit_identity_case(2, 3, 49200);
}

// Only out_bf16 requested (core_out and out_f32 null — what the engine does):
// the kernel must run and land within bf16 rounding of the reference o_norm.
TEST(KdaDecodeKernel, NullOptionalOutputs) {
    REQUIRES_GPU();
    const int H = 2;
    const KdaParams p = ref_params(H);
    const int C = p.channels();
    const size_t sn = static_cast<size_t>(H) * D * D;
    const ScanKernelInputs in = make_scan_kernel_inputs(H, 1, 48000);

    KdaState st = KdaState::zeros(p);
    st.s = in.s0;
    std::vector<float> ref_core(C), ref_onorm(C);
    recurrent_step(p, in.q.data(), in.k.data(), in.v.data(), in.raw_g.data(), in.beta.data(),
                   in.a_log.data(), in.dt_bias.data(), st, ref_core.data());
    gated_rmsnorm(p, ref_core.data(), in.g2.data(), in.onorm_w.data(), 1, ref_onorm.data());

    DevBag bag;
    __nv_bfloat16* out = bag.bf16z(C);
    sl::KdaDecodeStepParams dp{};
    dp.q = bag.f32(in.q);
    dp.k = bag.f32(in.k);
    dp.v = bag.f32(in.v);
    dp.raw_g = bag.bf16(in.raw_g);
    dp.beta = bag.bf16(in.beta);
    dp.g2 = bag.bf16(in.g2);
    dp.a_log = bag.f32(in.a_log);
    dp.dt_bias = bag.f32(in.dt_bias);
    dp.onorm_w = bag.bf16(in.onorm_w);
    dp.state_base = bag.f32(in.s0);
    dp.state_slot_stride = static_cast<int64_t>(sn);
    dp.slots = nullptr;
    dp.core_out = nullptr;
    dp.out_bf16 = out;
    dp.out_f32 = nullptr;
    dp.batch = 1;
    dp.num_heads = H;
    dp.lower_bound = kLowerBound;
    dp.l2_eps = kL2Eps;
    dp.onorm_eps = kONormEps;
    dp.scale = kda_scale();
    lc::launch_kda_decode_step(dp, nullptr);
    ASSERT_EQ(cudaDeviceSynchronize(), cudaSuccess);

    // bf16 has ~8 mantissa bits: the band is the storage format, not the math.
    expect_close(download_bf16_as_f32(out, C), ref_onorm, 4e-3, 8e-3,
                 "decode onorm (bf16 out only)");
}

// ═══════════════════════════════════════════════════════════════════════════
// (i) Chunk-parallel prefill scan — launch_kda_chunked_scan (agreement gate)
// ═══════════════════════════════════════════════════════════════════════════

/// The GPU chunked scan against BOTH CPU paths: the chunked reference (same
/// decomposition, so the tighter band) and the recurrent reference (the
/// "obviously right" path, band widened by the WY reassociation).
void chunk_scan_case(int heads, int t_len, uint64_t seed) {
    const KdaParams p = ref_params(heads);
    const int C = p.channels();
    const size_t n = static_cast<size_t>(t_len) * C;
    const size_t sn = static_cast<size_t>(heads) * D * D;
    const ScanKernelInputs in = make_scan_kernel_inputs(heads, t_len, seed);

    KdaState st_chk = KdaState::zeros(p);
    st_chk.s = in.s0;
    std::vector<float> core_chk(n, 0.0f);
    chunked_scan(p, in.q.data(), in.k.data(), in.v.data(), in.raw_g.data(), in.beta.data(),
                 in.a_log.data(), in.dt_bias.data(), t_len, st_chk, core_chk.data());

    KdaState st_rec = KdaState::zeros(p);
    st_rec.s = in.s0;
    std::vector<float> core_rec(n, 0.0f);
    recurrent_scan(p, in.q.data(), in.k.data(), in.v.data(), in.raw_g.data(), in.beta.data(),
                   in.a_log.data(), in.dt_bias.data(), t_len, st_rec, core_rec.data());

    DevBag bag;
    const size_t ws_bytes = lc::kda_prefill_workspace_bytes(t_len, heads);
    float* state = bag.f32(in.s0);
    float* core = bag.f32z(n);
    sl::KdaChunkedScanParams sp{};
    sp.q = bag.f32(in.q);
    sp.k = bag.f32(in.k);
    sp.v = bag.f32(in.v);
    sp.raw_g = bag.bf16(in.raw_g);
    sp.beta = bag.bf16(in.beta);
    sp.a_log = bag.f32(in.a_log);
    sp.dt_bias = bag.f32(in.dt_bias);
    sp.state = state;
    sp.core_out = core;
    sp.workspace = bag.raw(ws_bytes);
    sp.workspace_bytes = ws_bytes;
    sp.t_len = t_len;
    sp.num_heads = heads;
    sp.lower_bound = kLowerBound;
    sp.l2_eps = kL2Eps;
    sp.scale = kda_scale();
    lc::launch_kda_chunked_scan(sp, nullptr);
    ASSERT_EQ(cudaDeviceSynchronize(), cudaSuccess);

    const auto gcore = download<float>(core, n);
    const auto gstate = download<float>(state, sn);
    char lbl[128];
    std::snprintf(lbl, sizeof(lbl), "chunk H=%d T=%d core vs chunked", heads, t_len);
    expect_close(gcore, core_chk, 2e-5, 2e-4, lbl);
    std::snprintf(lbl, sizeof(lbl), "chunk H=%d T=%d state vs chunked", heads, t_len);
    expect_close(gstate, st_chk.s, 2e-5, 2e-4, lbl);
    std::snprintf(lbl, sizeof(lbl), "chunk H=%d T=%d core vs recurrent", heads, t_len);
    expect_close(gcore, core_rec, 3e-5, 3e-4, lbl);
    std::snprintf(lbl, sizeof(lbl), "chunk H=%d T=%d state vs recurrent", heads, t_len);
    expect_close(gstate, st_rec.s, 3e-5, 3e-4, lbl);
}

TEST(KdaChunkScan, SingleToken) {
    REQUIRES_GPU();
    chunk_scan_case(2, 1, 50000);
}

TEST(KdaChunkScan, PartialChunk) {
    REQUIRES_GPU();
    chunk_scan_case(2, 63, 51000);
}

TEST(KdaChunkScan, ExactChunk) {
    REQUIRES_GPU();
    chunk_scan_case(2, 64, 52000);
}

TEST(KdaChunkScan, MultiChunkTail) {
    REQUIRES_GPU();
    chunk_scan_case(2, 150, 53000);  // 64 + 64 + 22
}

TEST(KdaChunkScan, ModelGeometry) {
    REQUIRES_GPU();
    chunk_scan_case(4, 144, 54000);  // the golden geometry
}

// ═══════════════════════════════════════════════════════════════════════════
// Chunk-64 state carry — the BITWISE property GF3.8 / GF3.12 stand on
// ═══════════════════════════════════════════════════════════════════════════

struct CarryArms {
    std::vector<float> core_one, state_one, core_split, state_split;
};

/// One-shot launch of `t_len` vs two launches (split + rest) carrying the fp32
/// state through global memory. Each arm gets its OWN zeroed workspace so a
/// workspace-reuse artifact can never masquerade as a carry property.
CarryArms run_carry(int heads, int t_len, int split, uint64_t seed) {
    const KdaParams p = ref_params(heads);
    const int C = p.channels();
    const size_t n = static_cast<size_t>(t_len) * C;
    const size_t sn = static_cast<size_t>(heads) * D * D;
    const ScanKernelInputs in = make_scan_kernel_inputs(heads, t_len, seed);

    DevBag bag;
    const float* q = bag.f32(in.q);
    const float* k = bag.f32(in.k);
    const float* v = bag.f32(in.v);
    const __nv_bfloat16* rg = bag.bf16(in.raw_g);
    const __nv_bfloat16* bt = bag.bf16(in.beta);
    const float* alog = bag.f32(in.a_log);
    const float* dtb = bag.f32(in.dt_bias);
    const size_t ws_bytes = lc::kda_prefill_workspace_bytes(t_len, heads);
    void* ws_one = bag.raw(ws_bytes);
    void* ws_split = bag.raw(ws_bytes);

    float* state_one = bag.f32(in.s0);
    float* core_one = bag.f32z(n);
    float* state_split = bag.f32(in.s0);
    float* core_split = bag.f32z(n);

    auto scan = [&](float* state, float* core, void* ws, int t0, int len) {
        sl::KdaChunkedScanParams sp{};
        sp.q = q + static_cast<size_t>(t0) * C;
        sp.k = k + static_cast<size_t>(t0) * C;
        sp.v = v + static_cast<size_t>(t0) * C;
        sp.raw_g = rg + static_cast<size_t>(t0) * C;
        sp.beta = bt + static_cast<size_t>(t0) * heads;
        sp.a_log = alog;
        sp.dt_bias = dtb;
        sp.state = state;
        sp.core_out = core + static_cast<size_t>(t0) * C;
        sp.workspace = ws;
        sp.workspace_bytes = ws_bytes;
        sp.t_len = len;
        sp.num_heads = heads;
        sp.lower_bound = kLowerBound;
        sp.l2_eps = kL2Eps;
        sp.scale = kda_scale();
        lc::launch_kda_chunked_scan(sp, nullptr);
    };

    scan(state_one, core_one, ws_one, 0, t_len);
    scan(state_split, core_split, ws_split, 0, split);
    scan(state_split, core_split, ws_split, split, t_len - split);
    EXPECT_EQ(cudaDeviceSynchronize(), cudaSuccess);

    CarryArms a;
    a.core_one = download<float>(core_one, n);
    a.state_one = download<float>(state_one, sn);
    a.core_split = download<float>(core_split, n);
    a.state_split = download<float>(state_split, sn);
    return a;
}

// Split at a multiple of 64: identical chunk grid, exact fp32 state round-trip
// through global memory => BIT-FOR-BIT identical. This is the invariant the
// state pool (GF3.8) and checkpoints (GF3.12) are built on; a tolerance here
// would silently permit its loss.
TEST(KdaChunkCarry, Chunk64SplitIsBitwise) {
    REQUIRES_GPU();
    const CarryArms a = run_carry(2, 128, 64, 55000);
    EXPECT_TRUE(bit_equal(a.core_one, a.core_split)) << "core differs across a 64-aligned split";
    EXPECT_TRUE(bit_equal(a.state_one, a.state_split))
        << "state differs across a 64-aligned split";
}

// Same property with a ragged tail (150 = 64 + 86 -> chunks 64|64|22 either
// way): still the same chunk grid, still bitwise.
TEST(KdaChunkCarry, Chunk64SplitTail) {
    REQUIRES_GPU();
    const CarryArms a = run_carry(2, 150, 64, 56000);
    EXPECT_TRUE(bit_equal(a.core_one, a.core_split)) << "core differs across split @64 of 150";
    EXPECT_TRUE(bit_equal(a.state_one, a.state_split)) << "state differs across split @64 of 150";
}

// Split at a NON-multiple of 64 re-grids the chunks (64|36 then 50 instead of
// 64|64|22), so the WY sums reassociate: tolerance-equal but NOT bitwise —
// exactly the CPU reference's ScanSplitBoundaries behaviour. Documenting the
// boundary keeps the engine from assuming arbitrary cut points are free.
TEST(KdaChunkCarry, UnalignedSplitToleranceOnly) {
    REQUIRES_GPU();
    const CarryArms a = run_carry(2, 150, 100, 57000);
    expect_close(a.core_split, a.core_one, 2e-5, 2e-4, "core (unaligned split @100)");
    expect_close(a.state_split, a.state_one, 2e-5, 2e-4, "state (unaligned split @100)");
    EXPECT_FALSE(bit_equal(a.core_one, a.core_split) && bit_equal(a.state_one, a.state_split))
        << "an unaligned split reproduced the one-shot run bitwise — the chunk grid must "
           "have stopped depending on the launch origin; re-derive the carry contract";
}

// ═══════════════════════════════════════════════════════════════════════════
// Goldens — the full 152-token protocol on GPU against the committed fixtures
// ═══════════════════════════════════════════════════════════════════════════

struct GoldenSet {
    std::vector<float> prefill_core, prefill_onorm, state_after_prefill;
    std::vector<float> conv_q, conv_k, conv_v;
    std::vector<float> decode_core, decode_onorm, state_after_decode;
};

constexpr int kGoldT = 152, kGoldPre = 144, kGoldDec = 8, kGoldH = 4, kGoldD = 128;
constexpr size_t kGoldTok = static_cast<size_t>(kGoldH) * kGoldD;  // 512

GoldenSet load_goldens(const std::string& prefix) {
    const std::string base = "test-data/kda-goldens/" + prefix;
    GoldenSet g;
    g.prefill_core = load_f32(base + "prefill_core.bin", kGoldPre * kGoldTok);
    g.prefill_onorm = load_f32(base + "prefill_onorm.bin", kGoldPre * kGoldTok);
    g.state_after_prefill = load_f32(base + "state_after_prefill.bin",
                                     kGoldH * static_cast<size_t>(kGoldD) * kGoldD);
    g.conv_q = load_f32(base + "conv_state_q.bin", kGoldTok * 3);
    g.conv_k = load_f32(base + "conv_state_k.bin", kGoldTok * 3);
    g.conv_v = load_f32(base + "conv_state_v.bin", kGoldTok * 3);
    g.decode_core = load_f32(base + "decode_core.bin", kGoldDec * kGoldTok);
    g.decode_onorm = load_f32(base + "decode_onorm.bin", kGoldDec * kGoldTok);
    g.state_after_decode = load_f32(base + "state_after_decode.bin",
                                    kGoldH * static_cast<size_t>(kGoldD) * kGoldD);
    return g;
}

/// The golden protocol, entirely on the GPU:
///   raw bf16 q/k/v -> conv prefill(144) -> chunked scan(144) -> o_norm(144),
///   then 8 x (conv decode + fused decode step), batch 1.
/// Every output family is checked against the fixture generated by the
/// independent NumPy transcription (tools/gen_kda_golden.py).
void run_gpu_golden(const ScanInputs& in, const GoldenSet& g, double fs, double fe,
                    const std::string& label) {
    const KdaParams p = ref_params(kGoldH);
    const int C = p.channels();  // 512
    const size_t n_all = static_cast<size_t>(kGoldT) * C;
    const size_t rn = static_cast<size_t>(C) * 3;
    const size_t sn = static_cast<size_t>(kGoldH) * kGoldD * kGoldD;

    const std::vector<float> zeros_ring(rn, 0.0f);
    const std::vector<float> zeros_state(sn, 0.0f);

    DevBag bag;
    const __nv_bfloat16* xq = bag.bf16(in.q);
    const __nv_bfloat16* xk = bag.bf16(in.k);
    const __nv_bfloat16* xv = bag.bf16(in.v);
    const __nv_bfloat16* wq = bag.bf16(in.conv_wq);
    const __nv_bfloat16* wk = bag.bf16(in.conv_wk);
    const __nv_bfloat16* wv = bag.bf16(in.conv_wv);
    float* rq = bag.f32(ring_ref_to_gpu(in.cs_q.empty() ? zeros_ring : in.cs_q, C));
    float* rk = bag.f32(ring_ref_to_gpu(in.cs_k.empty() ? zeros_ring : in.cs_k, C));
    float* rv = bag.f32(ring_ref_to_gpu(in.cs_v.empty() ? zeros_ring : in.cs_v, C));
    // Post-conv activations for ALL 152 tokens: the prefill launch fills rows
    // [0,144), each decode step fills its own row.
    float* cq = bag.f32z(n_all);
    float* ck = bag.f32z(n_all);
    float* cv = bag.f32z(n_all);

    const __nv_bfloat16* rg = bag.bf16(in.raw_g);
    const __nv_bfloat16* bt = bag.bf16(in.beta);
    const __nv_bfloat16* g2 = bag.bf16(in.g2);
    const float* alog = bag.f32(in.a_log);
    const float* dtb = bag.f32(in.dt_bias);
    const __nv_bfloat16* ow = bag.bf16(in.onorm_w);
    float* state = bag.f32(in.s0.empty() ? zeros_state : in.s0);
    float* core = bag.f32z(n_all);
    float* onorm = bag.f32z(n_all);
    const size_t ws_bytes = lc::kda_prefill_workspace_bytes(kGoldPre, kGoldH);
    void* ws = bag.raw(ws_bytes);

    {  // conv prefill over the first 144 tokens
        sl::KdaConvPrefillParams cp{};
        cp.x_q = xq; cp.x_k = xk; cp.x_v = xv;
        cp.w_q = wq; cp.w_k = wk; cp.w_v = wv;
        cp.ring_q = rq; cp.ring_k = rk; cp.ring_v = rv;
        cp.out_q = cq; cp.out_k = ck; cp.out_v = cv;
        cp.t_len = kGoldPre;
        cp.channels = C;
        lc::launch_kda_conv_prefill(cp, nullptr);
    }
    {  // chunked scan over the same 144 tokens
        sl::KdaChunkedScanParams sp{};
        sp.q = cq; sp.k = ck; sp.v = cv;
        sp.raw_g = rg;
        sp.beta = bt;
        sp.a_log = alog;
        sp.dt_bias = dtb;
        sp.state = state;
        sp.core_out = core;
        sp.workspace = ws;
        sp.workspace_bytes = ws_bytes;
        sp.t_len = kGoldPre;
        sp.num_heads = kGoldH;
        sp.lower_bound = kLowerBound;
        sp.l2_eps = kL2Eps;
        sp.scale = kda_scale();
        lc::launch_kda_chunked_scan(sp, nullptr);
    }
    {  // gated RMSNorm (f32 tap — bf16 rounding would mask sub-1e-3 error)
        sl::KdaGatedRmsNormParams np{};
        np.core = core;
        np.g2 = g2;
        np.w = ow;
        np.out_bf16 = nullptr;
        np.out_f32 = onorm;
        np.t_len = kGoldPre;
        np.num_heads = kGoldH;
        np.eps = kONormEps;
        lc::launch_kda_gated_rmsnorm(np, nullptr);
    }
    ASSERT_EQ(cudaDeviceSynchronize(), cudaSuccess);

    expect_close(download<float>(core, kGoldPre * kGoldTok), g.prefill_core, fs, fe,
                 label + " prefill_core");
    expect_close(download<float>(onorm, kGoldPre * kGoldTok), g.prefill_onorm, fs, fe,
                 label + " prefill_onorm");
    expect_close(download<float>(state, sn), g.state_after_prefill, fs, fe,
                 label + " state_after_prefill");

    // Conv rings hold the last three RAW inputs: exact, once transposed out of
    // the GPU's [3][C] into the fixture's [C][3].
    const auto ring_q = ring_gpu_to_ref(download<float>(rq, rn), C);
    const auto ring_k = ring_gpu_to_ref(download<float>(rk, rn), C);
    const auto ring_v = ring_gpu_to_ref(download<float>(rv, rn), C);
    expect_close(ring_q, g.conv_q, fs, fe, label + " conv_state_q");
    expect_close(ring_k, g.conv_k, fs, fe, label + " conv_state_k");
    expect_close(ring_v, g.conv_v, fs, fe, label + " conv_state_v");
    for (size_t i = 0; i < rn; ++i) {
        ASSERT_EQ(ring_q[i], g.conv_q[i]) << label << " conv_state_q @" << i;
        ASSERT_EQ(ring_k[i], g.conv_k[i]) << label << " conv_state_k @" << i;
        ASSERT_EQ(ring_v[i], g.conv_v[i]) << label << " conv_state_v @" << i;
    }

    // Decode leg: 8 tokens, one conv-decode + one fused step each.
    for (int t = kGoldPre; t < kGoldT; ++t) {
        const size_t off = static_cast<size_t>(t) * C;
        sl::KdaConvDecodeParams dp{};
        dp.x_q = xq + off; dp.x_k = xk + off; dp.x_v = xv + off;
        dp.w_q = wq; dp.w_k = wk; dp.w_v = wv;
        dp.ring_q = rq; dp.ring_k = rk; dp.ring_v = rv;
        dp.slots = nullptr;
        dp.ring_slot_stride = static_cast<int64_t>(rn);
        dp.out_q = cq + off; dp.out_k = ck + off; dp.out_v = cv + off;
        dp.batch = 1;
        dp.channels = C;
        lc::launch_kda_conv_decode(dp, nullptr);

        sl::KdaDecodeStepParams sp{};
        sp.q = cq + off; sp.k = ck + off; sp.v = cv + off;
        sp.raw_g = rg + off;
        sp.beta = bt + static_cast<size_t>(t) * kGoldH;
        sp.g2 = g2 + off;
        sp.a_log = alog;
        sp.dt_bias = dtb;
        sp.onorm_w = ow;
        sp.state_base = state;
        sp.state_slot_stride = static_cast<int64_t>(sn);
        sp.slots = nullptr;
        sp.core_out = core + off;
        sp.out_bf16 = nullptr;
        sp.out_f32 = onorm + off;
        sp.batch = 1;
        sp.num_heads = kGoldH;
        sp.lower_bound = kLowerBound;
        sp.l2_eps = kL2Eps;
        sp.onorm_eps = kONormEps;
        sp.scale = kda_scale();
        lc::launch_kda_decode_step(sp, nullptr);
    }
    ASSERT_EQ(cudaDeviceSynchronize(), cudaSuccess);

    expect_close(download<float>(core + kGoldPre * kGoldTok, kGoldDec * kGoldTok),
                 g.decode_core, fs, fe, label + " decode_core");
    expect_close(download<float>(onorm + kGoldPre * kGoldTok, kGoldDec * kGoldTok),
                 g.decode_onorm, fs, fe, label + " decode_onorm");
    expect_close(download<float>(state, sn), g.state_after_decode, fs, fe,
                 label + " state_after_decode");
}

/// Golden case A inputs — seeds 101..116, exactly kda_reference_test.cpp's.
ScanInputs make_golden_synth_inputs() {
    const KdaParams p = ref_params(kGoldH);
    const size_t n = static_cast<size_t>(kGoldT) * p.channels();
    const size_t c = p.channels();
    ScanInputs in;
    in.q = synth(101, n, -1.0f, 1.0f, true);
    in.k = synth(102, n, -1.0f, 1.0f, true);
    in.v = synth(103, n, -1.0f, 1.0f, true);
    in.raw_g = synth(104, n, -3.0f, 3.0f, true);
    in.g2 = synth(105, n, -2.0f, 2.0f, true);
    in.beta = synth(106, static_cast<size_t>(kGoldT) * kGoldH, -2.0f, 2.0f, true);
    in.a_log = synth(107, kGoldH, -1.0f, 1.5f, false);
    in.dt_bias = synth(108, c, -1.0f, 1.0f, false);
    in.conv_wq = synth(109, c * 4, -0.5f, 0.5f, true);
    in.conv_wk = synth(110, c * 4, -0.5f, 0.5f, true);
    in.conv_wv = synth(111, c * 4, -0.5f, 0.5f, true);
    in.onorm_w = synth(112, kGoldD, 0.5f, 1.5f, true);
    in.s0 = synth(113, static_cast<size_t>(kGoldH) * kGoldD * kGoldD, -1.0f, 1.0f, false);
    in.cs_q = synth(114, c * 3, -1.0f, 1.0f, true);
    in.cs_k = synth(115, c * 3, -1.0f, 1.0f, true);
    in.cs_v = synth(116, c * 3, -1.0f, 1.0f, true);
    return in;
}

// Case A: fully synthetic inputs, nonzero initial state and conv rings. Bands
// start at the CPU chunked-path golden bands (3e-5 / 3e-4) — the GPU prefill
// leg is the chunked decomposition, so that is the right starting point.
TEST(KdaGoldenSynth, FullProtocol) {
    REQUIRES_GPU();
    const GoldenSet g = load_goldens("synth_");
    if (g.prefill_core.empty()) GTEST_FAIL() << "goldens missing — run tools/gen_kda_golden.py";
    const ScanInputs in = make_golden_synth_inputs();
    run_gpu_golden(in, g, 3e-5, 3e-4, "synth/gpu");
}

// Case B: REAL GLM-5.3-Flash layer-0 KDA tensors (heads {0,17,42,63}) drive
// the gate/conv/o_norm; activations synthetic; raw_g/g2 through the REAL
// f_b/g_b low-rank mats. Zero initial state and rings. Bands start at the CPU
// real-case bands (4e-4 / 4e-3): the low-rank GEMM is recomputed here with
// sequential fp32 dots while the generator used numpy pairwise sums, so a gate
// input can land 1 bf16 ulp apart and the real steep gates (exp(A_log) up to
// 8.2) amplify that — see kda_reference_test.cpp's GoldenRealLayer0Case.
TEST(KdaGoldenReal, FullProtocol) {
    REQUIRES_GPU();
    const GoldenSet g = load_goldens("real_");
    if (g.prefill_core.empty()) GTEST_FAIL() << "goldens missing — run tools/gen_kda_golden.py";

    const std::string fx = "test-data/GLM-5.3-Flash/kda-layer0/";
    const int kRealHeads[kGoldH] = {0, 17, 42, 63};
    const auto a_log_all = load_f32(fx + "A_log.bin", 64);
    const auto dt_bias_all = load_f32(fx + "dt_bias.bin", 8192);
    const auto conv_q_all = load_bf16_as_f32(fx + "q_conv1d_weight.bin", 8192 * 4);
    const auto conv_k_all = load_bf16_as_f32(fx + "k_conv1d_weight.bin", 8192 * 4);
    const auto conv_v_all = load_bf16_as_f32(fx + "v_conv1d_weight.bin", 8192 * 4);
    const auto onorm_w = load_bf16_as_f32(fx + "o_norm_weight.bin", 128);
    const auto f_b = load_bf16_as_f32(fx + "f_b_proj_weight.bin", 8192 * 128);
    const auto g_b = load_bf16_as_f32(fx + "g_b_proj_weight.bin", 8192 * 128);
    if (a_log_all.empty() || f_b.empty()) {
        GTEST_FAIL() << "real layer-0 fixture missing — run tools/fetch_glm53_kda_layer0.py";
    }

    ScanInputs in;
    const size_t n = static_cast<size_t>(kGoldT) * kGoldTok;
    in.q = synth(303, n, -1.0f, 1.0f, true);
    in.k = synth(304, n, -1.0f, 1.0f, true);
    in.v = synth(305, n, -1.0f, 1.0f, true);
    in.beta = synth(306, static_cast<size_t>(kGoldT) * kGoldH, -2.0f, 2.0f, true);
    in.g2.assign(n, 0.0f);
    in.raw_g.assign(n, 0.0f);
    const auto fa = synth(301, static_cast<size_t>(kGoldT) * 128, -1.0f, 1.0f, true);
    const auto ga = synth(302, static_cast<size_t>(kGoldT) * 128, -1.0f, 1.0f, true);
    for (int t = 0; t < kGoldT; ++t) {
        for (int h = 0; h < kGoldH; ++h) {
            const int rh = kRealHeads[h];
            for (int dd = 0; dd < kGoldD; ++dd) {
                const size_t row = static_cast<size_t>(rh) * kGoldD + dd;
                float acc_f = 0, acc_g = 0;
                for (int j = 0; j < 128; ++j) {
                    acc_f += f_b[row * 128 + j] * fa[static_cast<size_t>(t) * 128 + j];
                    acc_g += g_b[row * 128 + j] * ga[static_cast<size_t>(t) * 128 + j];
                }
                const size_t o =
                    static_cast<size_t>(t) * kGoldTok + static_cast<size_t>(h) * kGoldD + dd;
                in.raw_g[o] = bf16_round(acc_f);
                in.g2[o] = bf16_round(acc_g);
            }
        }
    }
    in.a_log.resize(kGoldH);
    in.dt_bias.resize(kGoldTok);
    in.conv_wq.resize(kGoldTok * 4);
    in.conv_wk.resize(kGoldTok * 4);
    in.conv_wv.resize(kGoldTok * 4);
    for (int h = 0; h < kGoldH; ++h) {
        const int rh = kRealHeads[h];
        in.a_log[h] = a_log_all[rh];
        for (int dd = 0; dd < kGoldD; ++dd) {
            in.dt_bias[static_cast<size_t>(h) * kGoldD + dd] =
                dt_bias_all[static_cast<size_t>(rh) * kGoldD + dd];
            for (int j = 0; j < 4; ++j) {
                const size_t src = (static_cast<size_t>(rh) * kGoldD + dd) * 4 + j;
                const size_t dst = (static_cast<size_t>(h) * kGoldD + dd) * 4 + j;
                in.conv_wq[dst] = conv_q_all[src];
                in.conv_wk[dst] = conv_k_all[src];
                in.conv_wv[dst] = conv_v_all[src];
            }
        }
    }
    in.onorm_w = onorm_w;
    // s0 / cs_* stay empty => zero initial recurrent and conv state.
    run_gpu_golden(in, g, 4e-4, 4e-3, "real/gpu");
}

// ═══════════════════════════════════════════════════════════════════════════
// Prefill -> decode continuity: the state handoff GF3.9's hybrid execution
// makes on every request (chunked prefill, then O(1) steps).
// ═══════════════════════════════════════════════════════════════════════════

TEST(KdaPrefillDecodeContinuity, ChunkedThenDecode) {
    REQUIRES_GPU();
    const int H = 2, t_pre = 100, t_dec = 10, T = t_pre + t_dec;
    const KdaParams p = ref_params(H);
    const int C = p.channels();
    const size_t n = static_cast<size_t>(T) * C;
    const size_t rn = static_cast<size_t>(C) * 3;
    const size_t sn = static_cast<size_t>(H) * D * D;
    const ScanInputs in = make_inputs(p, T, 58000);

    // CPU arbiter: the pure recurrent scan of all 110 tokens.
    const ScanResult ref = run_ref_scan(p, ScanPath::kRecurrent, in, T);

    DevBag bag;
    const __nv_bfloat16* xq = bag.bf16(in.q);
    const __nv_bfloat16* xk = bag.bf16(in.k);
    const __nv_bfloat16* xv = bag.bf16(in.v);
    const __nv_bfloat16* wq = bag.bf16(in.conv_wq);
    const __nv_bfloat16* wk = bag.bf16(in.conv_wk);
    const __nv_bfloat16* wv = bag.bf16(in.conv_wv);
    float* rq = bag.f32(ring_ref_to_gpu(in.cs_q, C));
    float* rk = bag.f32(ring_ref_to_gpu(in.cs_k, C));
    float* rv = bag.f32(ring_ref_to_gpu(in.cs_v, C));
    float* cq = bag.f32z(n);
    float* ck = bag.f32z(n);
    float* cv = bag.f32z(n);
    const __nv_bfloat16* rg = bag.bf16(in.raw_g);
    const __nv_bfloat16* bt = bag.bf16(in.beta);
    const __nv_bfloat16* g2 = bag.bf16(in.g2);
    const float* alog = bag.f32(in.a_log);
    const float* dtb = bag.f32(in.dt_bias);
    const __nv_bfloat16* ow = bag.bf16(in.onorm_w);
    float* state = bag.f32(in.s0);
    float* core = bag.f32z(n);
    float* onorm = bag.f32z(n);
    const size_t ws_bytes = lc::kda_prefill_workspace_bytes(t_pre, H);
    void* ws = bag.raw(ws_bytes);

    {
        sl::KdaConvPrefillParams cp{};
        cp.x_q = xq; cp.x_k = xk; cp.x_v = xv;
        cp.w_q = wq; cp.w_k = wk; cp.w_v = wv;
        cp.ring_q = rq; cp.ring_k = rk; cp.ring_v = rv;
        cp.out_q = cq; cp.out_k = ck; cp.out_v = cv;
        cp.t_len = t_pre;
        cp.channels = C;
        lc::launch_kda_conv_prefill(cp, nullptr);
    }
    {
        sl::KdaChunkedScanParams sp{};
        sp.q = cq; sp.k = ck; sp.v = cv;
        sp.raw_g = rg;
        sp.beta = bt;
        sp.a_log = alog;
        sp.dt_bias = dtb;
        sp.state = state;
        sp.core_out = core;
        sp.workspace = ws;
        sp.workspace_bytes = ws_bytes;
        sp.t_len = t_pre;
        sp.num_heads = H;
        sp.lower_bound = kLowerBound;
        sp.l2_eps = kL2Eps;
        sp.scale = kda_scale();
        lc::launch_kda_chunked_scan(sp, nullptr);
    }
    {
        sl::KdaGatedRmsNormParams np{};
        np.core = core;
        np.g2 = g2;
        np.w = ow;
        np.out_bf16 = nullptr;
        np.out_f32 = onorm;
        np.t_len = t_pre;
        np.num_heads = H;
        np.eps = kONormEps;
        lc::launch_kda_gated_rmsnorm(np, nullptr);
    }
    for (int t = t_pre; t < T; ++t) {
        const size_t off = static_cast<size_t>(t) * C;
        sl::KdaConvDecodeParams dp{};
        dp.x_q = xq + off; dp.x_k = xk + off; dp.x_v = xv + off;
        dp.w_q = wq; dp.w_k = wk; dp.w_v = wv;
        dp.ring_q = rq; dp.ring_k = rk; dp.ring_v = rv;
        dp.slots = nullptr;
        dp.ring_slot_stride = static_cast<int64_t>(rn);
        dp.out_q = cq + off; dp.out_k = ck + off; dp.out_v = cv + off;
        dp.batch = 1;
        dp.channels = C;
        lc::launch_kda_conv_decode(dp, nullptr);

        sl::KdaDecodeStepParams sp{};
        sp.q = cq + off; sp.k = ck + off; sp.v = cv + off;
        sp.raw_g = rg + off;
        sp.beta = bt + static_cast<size_t>(t) * H;
        sp.g2 = g2 + off;
        sp.a_log = alog;
        sp.dt_bias = dtb;
        sp.onorm_w = ow;
        sp.state_base = state;
        sp.state_slot_stride = static_cast<int64_t>(sn);
        sp.slots = nullptr;
        sp.core_out = core + off;
        sp.out_bf16 = nullptr;
        sp.out_f32 = onorm + off;
        sp.batch = 1;
        sp.num_heads = H;
        sp.lower_bound = kLowerBound;
        sp.l2_eps = kL2Eps;
        sp.onorm_eps = kONormEps;
        sp.scale = kda_scale();
        lc::launch_kda_decode_step(sp, nullptr);
    }
    ASSERT_EQ(cudaDeviceSynchronize(), cudaSuccess);

    expect_close(download<float>(core, n), ref.core, 3e-5, 3e-4, "continuity core");
    expect_close(download<float>(onorm, n), ref.onorm, 3e-5, 3e-4, "continuity onorm");
    expect_close(download<float>(state, sn), ref.st.s, 3e-5, 3e-4, "continuity state");
    const auto ring_q = ring_gpu_to_ref(download<float>(rq, rn), C);
    for (size_t i = 0; i < rn; ++i) ASSERT_EQ(ring_q[i], ref.cq.ring[i]) << "ring_q @" << i;
}

// ═══════════════════════════════════════════════════════════════════════════
// Dispatch refusals (CPU-only: the wrappers validate geometry and throw BEFORE
// any launch, so the device pointers here are deliberately fake and never
// dereferenced — this suite stays out of the GPU ctest bucket).
// ═══════════════════════════════════════════════════════════════════════════

float* const kFakeF32 = reinterpret_cast<float*>(0x10);
const __nv_bfloat16* const kFakeBf16 = reinterpret_cast<const __nv_bfloat16*>(0x10);
void* const kFakeWs = reinterpret_cast<void*>(0x10);

sl::KdaChunkedScanParams scan_params(int t_len, int heads) {
    sl::KdaChunkedScanParams p{};
    p.q = kFakeF32;
    p.k = kFakeF32;
    p.v = kFakeF32;
    p.raw_g = kFakeBf16;
    p.beta = kFakeBf16;
    p.a_log = kFakeF32;
    p.dt_bias = kFakeF32;
    p.state = kFakeF32;
    p.core_out = kFakeF32;
    p.workspace = kFakeWs;
    p.workspace_bytes =
        lc::kda_prefill_workspace_bytes(std::max(t_len, 1), std::max(heads, 1));
    p.t_len = t_len;
    p.num_heads = heads;
    p.lower_bound = kLowerBound;
    p.l2_eps = kL2Eps;
    p.scale = kda_scale();
    return p;
}

sl::KdaDecodeStepParams decode_params(int batch, int heads) {
    sl::KdaDecodeStepParams p{};
    p.q = kFakeF32;
    p.k = kFakeF32;
    p.v = kFakeF32;
    p.raw_g = kFakeBf16;
    p.beta = kFakeBf16;
    p.g2 = kFakeBf16;
    p.a_log = kFakeF32;
    p.dt_bias = kFakeF32;
    p.onorm_w = kFakeBf16;
    p.state_base = kFakeF32;
    p.state_slot_stride = static_cast<int64_t>(std::max(heads, 1)) * D * D;
    p.slots = nullptr;
    p.core_out = kFakeF32;
    p.out_bf16 = nullptr;
    p.out_f32 = kFakeF32;
    p.batch = batch;
    p.num_heads = heads;
    p.lower_bound = kLowerBound;
    p.l2_eps = kL2Eps;
    p.onorm_eps = kONormEps;
    p.scale = kda_scale();
    return p;
}

sl::KdaConvPrefillParams conv_prefill_params(int t_len, int channels) {
    sl::KdaConvPrefillParams p{};
    p.x_q = kFakeBf16;
    p.x_k = kFakeBf16;
    p.x_v = kFakeBf16;
    p.w_q = kFakeBf16;
    p.w_k = kFakeBf16;
    p.w_v = kFakeBf16;
    p.ring_q = kFakeF32;
    p.ring_k = kFakeF32;
    p.ring_v = kFakeF32;
    p.out_q = kFakeF32;
    p.out_k = kFakeF32;
    p.out_v = kFakeF32;
    p.t_len = t_len;
    p.channels = channels;
    return p;
}

sl::KdaConvDecodeParams conv_decode_params(int batch, int channels) {
    sl::KdaConvDecodeParams p{};
    p.x_q = kFakeBf16;
    p.x_k = kFakeBf16;
    p.x_v = kFakeBf16;
    p.w_q = kFakeBf16;
    p.w_k = kFakeBf16;
    p.w_v = kFakeBf16;
    p.ring_q = kFakeF32;
    p.ring_k = kFakeF32;
    p.ring_v = kFakeF32;
    p.slots = nullptr;
    p.ring_slot_stride = static_cast<int64_t>(3) * channels;
    p.out_q = kFakeF32;
    p.out_k = kFakeF32;
    p.out_v = kFakeF32;
    p.batch = batch;
    p.channels = channels;
    return p;
}

TEST(KdaDispatch, RejectsNonPositiveTokenCount) {
    EXPECT_THROW(lc::launch_kda_chunked_scan(scan_params(0, 4), nullptr), std::runtime_error);
    EXPECT_THROW(lc::launch_kda_chunked_scan(scan_params(-3, 4), nullptr), std::runtime_error);
    EXPECT_THROW(lc::launch_kda_conv_prefill(conv_prefill_params(0, 512), nullptr),
                 std::runtime_error);
    EXPECT_THROW(lc::launch_kda_conv_prefill(conv_prefill_params(-1, 512), nullptr),
                 std::runtime_error);
}

TEST(KdaDispatch, RejectsNonPositiveBatch) {
    EXPECT_THROW(lc::launch_kda_decode_step(decode_params(0, 4), nullptr), std::runtime_error);
    EXPECT_THROW(lc::launch_kda_decode_step(decode_params(-2, 4), nullptr), std::runtime_error);
}

TEST(KdaDispatch, RejectsNonPositiveHeadCount) {
    EXPECT_THROW(lc::launch_kda_chunked_scan(scan_params(64, 0), nullptr), std::runtime_error);
    EXPECT_THROW(lc::launch_kda_decode_step(decode_params(1, 0), nullptr), std::runtime_error);
}

TEST(KdaDispatch, RejectsBadWorkspace) {
    {
        sl::KdaChunkedScanParams p = scan_params(64, 4);
        p.workspace = nullptr;
        EXPECT_THROW(lc::launch_kda_chunked_scan(p, nullptr), std::runtime_error);
    }
    {
        sl::KdaChunkedScanParams p = scan_params(64, 4);
        p.workspace_bytes = 16;  // far below kda_prefill_workspace_bytes(64, 4)
        EXPECT_THROW(lc::launch_kda_chunked_scan(p, nullptr), std::runtime_error);
    }
}

TEST(KdaDispatch, RejectsUndersizedSlotStrides) {
    {
        sl::KdaDecodeStepParams p = decode_params(1, 4);
        p.state_slot_stride = static_cast<int64_t>(4) * D * D - 1;
        EXPECT_THROW(lc::launch_kda_decode_step(p, nullptr), std::runtime_error);
    }
    {
        sl::KdaConvDecodeParams p = conv_decode_params(1, 512);
        p.ring_slot_stride = static_cast<int64_t>(3) * 512 - 1;
        EXPECT_THROW(lc::launch_kda_conv_decode(p, nullptr), std::runtime_error);
    }
}

}  // namespace
